/* Isi BA Penghadapan yang disusun dari salinan penetapan (folder Drive "Daftar Penetapan Baru/Riau").
   Kunci = nomor penetapan. Baris: butir utama; "- " sub-butir; "-- " sub-sub-butir.
   {tgl:YYYY-MM-DD} dan {usia:YYYY-MM-DD} dihitung aplikasi (usia per tanggal sumpah). */
const BAP_SIAP_VERSI = 1;
const BAP_SIAP = {
'48/Pdt.P/2025/PN Pbr': [
'Bahwa penghadap bernama **JOANNA MURTHY REY**, lahir di Mentawai pada tanggal {tgl:1982-06-26} ({usia:1982-06-26}), agama Islam, pekerjaan Wiraswasta, bertempat tinggal di Komp. Wadya Graha I Blok O No. 8, RT 003 RW 007, Kelurahan Delima, Kecamatan Tampan, Kota Pekanbaru, Provinsi Riau, adalah anak kandung dari terampu;',
'Bahwa terampu bernama **BETTY UMAR**, lahir di Jakarta pada tanggal {tgl:1957-12-23} ({usia:1957-12-23}), adalah ibu kandung penghadap yang tinggal serumah dengan penghadap di alamat tersebut di atas;',
'Bahwa terampu mempunyai 4 (empat) orang anak, yaitu:',
'- **JEANIE AILANNA**, lahir di Pekanbaru pada tanggal {tgl:1980-06-27};',
'- **JOANNA MURTHY REY** (penghadap), lahir di Mentawai pada tanggal {tgl:1982-06-26};',
'- **INKA NAGARA**, lahir di Pekanbaru pada tanggal {tgl:1986-08-02};',
'- **IRYANDO DANOVAN**, lahir di Bukit Tinggi pada tanggal {tgl:1993-06-26};',
'Bahwa terampu menderita penyakit Possible Dementia Alzheimer disertai Hipertensi sebagaimana Surat Keterangan Dokter Rumah Sakit Umum Daerah Petala Bumi Nomor 445/RSUD-PB/4249, yang menyebabkan terampu sering lupa dengan kondisi yang semakin memburuk sesuai Catatan Perkembangan Pasien Terintegrasi (CPPT) rumah sakit tersebut, sehingga terampu tidak cakap melakukan perbuatan hukum;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk memenuhi persyaratan jual beli rumah milik terampu, karena rumah tersebut kondisinya kurang memadai dan terlalu besar untuk dihuni, sehingga hendak dijual untuk membeli rumah yang layak huni dan minimalis serta untuk biaya hidup dan pengobatan terampu;',
'Bahwa harta kekayaan milik terampu yang berkaitan dengan permohonan ini adalah sebagai berikut:',
'- Sebidang tanah dan bangunan dengan Sertifikat Hak Milik Nomor 793, terletak di Kelurahan Delima, Kecamatan Binawidya, Kota Pekanbaru, Provinsi Riau, atas nama **BETTY UMAR**;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 48/Pdt.P/2025/PN Pbr tanggal {tgl:2025-02-27}, penghadap telah ditetapkan sebagai Pengampu dari terampu **BETTY UMAR**, termasuk untuk menandatangani atau memberikan kuasa menjual sebidang tanah dan bangunan tersebut di atas;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'73/Pdt.P/2025/PN Pbr': [
'Bahwa penghadap bernama **MUSLIM MOHAMMAD**, lahir di Pekanbaru pada tanggal {tgl:1983-02-18} ({usia:1983-02-18}), agama Islam, pekerjaan Wiraswasta, bertempat tinggal di Jl. Inpres Gg. Gundaling, RT 003 RW 011, Kelurahan Perhentian Marpoyan Damai, Kecamatan Marpoyan Damai, Kota Pekanbaru, Provinsi Riau, adalah adik kandung dari terampu;',
'Bahwa penghadap dan terampu merupakan anak dari pasangan suami istri **JUSRI RAMLI** dan **RATNA JUWITA**, yang dari perkawinannya dikaruniai 4 (empat) orang anak, yaitu:',
'- **EBIET MOHAMMAD** (terampu), lahir di Pekanbaru pada tanggal {tgl:1979-12-22} ({usia:1979-12-22});',
'- **BONDAN MOHAMMAD**, lahir di Pekanbaru pada tanggal {tgl:1981-02-22};',
'- **MUSLIM MOHAMMAD** (penghadap), lahir di Pekanbaru pada tanggal {tgl:1983-02-18};',
'- **ANGGIA MURNI MOHAMMAD**, lahir di Pekanbaru pada tanggal {tgl:1984-11-16};',
'Bahwa kedua orang tua penghadap dan terampu telah meninggal dunia, yaitu:',
'- **JUSRI RAMLI** (ayah) meninggal dunia di Pekanbaru pada tanggal {tgl:2011-11-27}, berdasarkan Akta Kematian Nomor 1471-KM-11122014-0007 tanggal {tgl:2014-12-11} yang dikeluarkan oleh Dinas Kependudukan dan Pencatatan Sipil Kota Pekanbaru;',
'- **RATNA JUWITA** (ibu) meninggal dunia di Pekanbaru pada tanggal {tgl:2022-10-13}, berdasarkan Akta Kematian Nomor 1471-KM-03112022-0010 tanggal {tgl:2022-11-03} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru;',
'Bahwa terampu **EBIET MOHAMMAD** menderita gangguan kejiwaan sejak duduk di bangku SMP, pernah dirawat jalan di Rumah Sakit Jiwa Tampan sebagaimana Surat Keterangan Dirawat tanggal {tgl:2014-12-05} dan mengonsumsi obat Chlorpromazine, Trihexyphenidyl, dan Haloperidol sesuai Surat Keterangan Nomor 1914/PSBL/RH.02.02/9/2015;',
'Bahwa sejak ibu kandungnya meninggal dunia, terampu tidak lagi mengonsumsi obat tersebut, kondisinya menyerupai orang pikun, makan dan buang air di tempat, tidak dapat berkomunikasi maupun bersosialisasi dengan lingkungan, sering tertawa sendiri, dan dalam kesehariannya harus diawasi, sehingga tidak cakap melakukan perbuatan hukum;',
'Bahwa saat ini terampu tinggal bersama dan dirawat oleh penghadap;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk memenuhi persyaratan dokumen turun waris atas harta peninggalan almarhumah **RATNA JUWITA**, antara lain tanah dengan Sertifikat Hak Milik Nomor 04691, karena terampu tidak dapat bertindak sendiri akibat penyakit kejiwaan yang dideritanya;',
'Bahwa saudara kandung penghadap, **BONDAN MOHAMMAD** dan **ANGGIA MURNI MOHAMMAD**, telah memberikan kuasa kepada penghadap untuk mengurus penetapan pengampuan tersebut;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **LINDAWATI**, adik kandung ibu penghadap, menerangkan bahwa terampu menderita gangguan jiwa sejak SMP, kini tinggal bersama penghadap, tidak dapat berkomunikasi dan harus diawasi, serta bahwa almarhumah ibu penghadap memiliki harta warisan yang akan diurus turun warisnya;',
'- Saksi **ZUL ASRI**, Ketua RT di lingkungan tempat tinggal penghadap, menerangkan bahwa terampu menderita gangguan jiwa sejak SMP, tinggal bersama penghadap, dan tidak dapat berkomunikasi maupun bersosialisasi dengan lingkungan;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 73/Pdt.P/2025/PN Pbr tanggal {tgl:2025-03-20}, penghadap selaku saudara kandung telah ditetapkan sebagai Pengampu dari **EBIET MOHAMMAD** dan ditetapkan untuk bertindak melakukan penandatanganan/kuasa terhadap persyaratan turun waris;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'130/Pdt.P/2025/PN Pbr': [
'Bahwa penghadap bernama **YOLANDA OLIVIA AGNESIA S**, NIK 1403096110980010, perempuan, lahir di Duri pada tanggal {tgl:1998-10-21} ({usia:1998-10-21}), agama Katholik, pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Jl. Aur Kuning Perum Aur Kuning Blok K 1/2, RT 006 RW 003, Kelurahan Air Dingin, Kecamatan Bukit Raya, Kota Pekanbaru, adalah adik kandung dari terampu;',
'Bahwa penghadap telah menikah dengan **GUBTA PAUTAMA** sebagaimana Kutipan Akta Perkawinan, dan tercatat dalam Kartu Keluarga dengan **GUBTA PAUTAMA** selaku kepala keluarga;',
'Bahwa penghadap dan terampu merupakan anak dari pasangan suami istri yang sah **BILLIAN ANWAR HEDWIG. S** dan **LUSIA MARIA MAGDALENA. S**, yang semasa hidupnya bertempat tinggal di Komp. Merapi No. 9, RT 002 RW 003, Desa Pematang Pudu, Kecamatan Mandau, Kabupaten Bengkalis, Riau, dan dari perkawinan tersebut dikaruniai 3 (tiga) orang anak, yaitu:',
'- **PAULUS FELIX SITUMORANG** (terampu), lahir di Duri pada tanggal {tgl:1988-02-20};',
'- **YACOBUS NOVERIUS SITUMORANG**, lahir di Duri pada tanggal {tgl:1990-11-09};',
'- **YOLANDA OLIVIA AGNESIA S** (penghadap), lahir di Duri pada tanggal {tgl:1998-10-21};',
'Bahwa kedua orang tua penghadap telah meninggal dunia, yaitu:',
'- **BILLIAN ANWAR HEDWIG. S** (ayah) meninggal dunia di Pekanbaru pada tanggal {tgl:2021-01-17}, berdasarkan Akta Kematian Nomor 1471-KM-03022021-0011 yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru tanggal {tgl:2022-04-08};',
'- **LUSIA MARIA MAGDALENA. S** (ibu) meninggal dunia di Pekanbaru pada tanggal {tgl:2024-03-05}, berdasarkan Akta Kematian Nomor 1471-KM-15032024-0021 yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru tanggal {tgl:2024-04-29};',
'Bahwa dengan meninggalnya kedua orang tua tersebut, penghadap, terampu, dan **YACOBUS NOVERIUS SITUMORANG** merupakan ahli waris yang sah dari almarhum dan almarhumah;',
'Bahwa terampu bernama **PAULUS FELIX SITUMORANG**, NIK 1403092002880005, laki-laki, lahir di Duri pada tanggal {tgl:1988-02-20} ({usia:1988-02-20}), agama Katholik, tidak bekerja, beralamat KTP di Jl. Jayagiri No. 38, RT 01 RW 15, Kelurahan Jayagiri, Kecamatan Lembang, Kabupaten Bandung Barat, Jawa Barat, dan berdomisili di Jl. Karya Cipta No. B2, Kelurahan Air Dingin, Kecamatan Bukit Raya, Kota Pekanbaru, serta belum pernah menikah dan tidak mempunyai anak;',
'Bahwa terampu mengalami Autis atau Gangguan Spektrum Autisme (GSA) dan saat ini dirawat di Yayasan Pondok Anugerah Generasi Yosua sebagaimana Surat Keterangan Dirawat Nomor 001/SK/PAGY/V/2025 tanggal {tgl:2025-05-02}, karena kondisinya tidak stabil, harus dipantau setiap saat, dan wajib minum obat rutin 3 (tiga) kali sehari, sehingga terampu tidak cakap melakukan perbuatan hukum;',
'Bahwa semasa hidupnya orang tua penghadap meninggalkan harta warisan sebagai berikut:',
'- Sertifikat Hak Milik Nomor 6953, terletak di Perumahan Aur Kuning Blok K1 No. 2, Jalan Kaharuddin Nasution, Kelurahan Simpang Tiga (sekarang Kelurahan Air Dingin), Kecamatan Bukit Raya, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA. S**;',
'- Sertifikat Hak Milik Nomor 3879, terletak di Jalan Karya Cipta B2, Kelurahan Simpang Tiga (sekarang Kelurahan Air Dingin), Kecamatan Bukit Raya, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA SINAGA**;',
'- Sertifikat Hak Milik Nomor 4165, terletak di Jalan Karya 1 Gg. Pusri, Kelurahan Simpang Tiga (sekarang Kelurahan Air Dingin), Kecamatan Bukit Raya, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA SINAGA**;',
'- Sertifikat Hak Guna Bangunan Nomor 1255, terletak di Perumahan Sentosa Residence Blok D2 No. 3a, Jalan Abdul Malik, Kelurahan Sail, Kecamatan Tenayan Raya, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA SINAGA**;',
'- Sertifikat Hak Milik Nomor 569, terletak di Jalan Jenderal Sudirman, Kelurahan Babussalam, Kecamatan Mandau, Kabupaten Bengkalis, Riau, atas nama **LUSIA MARIA MAGDALENA. S**;',
'- Sertifikat Hak Pakai Nomor 00038, terletak di Jalan Pahlawan Kerja Gg. Matador II, Kelurahan Maharatu, Kecamatan Marpoyan Damai, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA. S**;',
'- Surat Ganti Kerugian Nomor 1.641/SGKT/V/2011, terletak di Kelurahan Balai Raja, Kecamatan Pinggir, Kabupaten Bengkalis, Riau, atas nama **LUSIA MARIA MAGDALENA SINAGA**;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk memenuhi persyaratan jual beli atas harta warisan tersebut, yang hasilnya akan digunakan untuk modal usaha, kebutuhan sehari-hari para ahli waris, serta biaya pengobatan terampu, sehingga Notaris/PPAT dapat menerima kuasa dari penghadap tanpa menghadirkan dan tanpa tanda tangan terampu;',
'Bahwa permohonan pengampuan tersebut telah mendapat persetujuan dari saudara kandung penghadap, **YACOBUS NOVERIUS SITUMORANG**, sebagaimana Surat Pernyataan Persetujuan tanggal {tgl:2025-05-02};',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **GUBTA PAUTAMA**, suami penghadap, menerangkan bahwa kedua orang tua penghadap telah meninggal dunia dengan meninggalkan harta warisan tersebut, bahwa terampu mengalami Autis (GSA), dirawat di Yayasan Pondok Anugerah Generasi Yosua, belum pernah menikah, serta tidak ada pihak yang keberatan atas permohonan ini;',
'- Saksi **R. RRO EVITA CITRADEWI**, ipar penghadap, memberikan keterangan yang bersesuaian mengenai ahli waris, harta warisan, kondisi terampu, dan persetujuan saudara kandung penghadap;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 130/Pdt.P/2025/PN Pbr tanggal {tgl:2025-05-14}, **PAULUS FELIX SITUMORANG** dinyatakan diletakkan di bawah pengampuan, dan penghadap selaku adik kandung ditetapkan sebagai Pengampu yang berhak bertindak untuk dan atas kepentingan hukum terampu, termasuk untuk menandatangani/memberikan kuasa menjual atas ketujuh bidang harta tersebut di atas;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'155/Pdt.P/2026/PN Pbr': [
'Bahwa penghadap bernama **AULIA RAHMA YUDI**, NIK 1471064306980021, perempuan, lahir di Pekanbaru pada tanggal {tgl:1998-06-03} ({usia:1998-06-03}), pekerjaan Wiraswasta, bertempat tinggal di Jl. Nelayan Gg. Sepat, RT 003 RW 010, Kelurahan Sri Meranti, Kecamatan Rumbai, Kota Pekanbaru, Provinsi Riau, adalah kakak kandung dari terampu;',
'Bahwa penghadap telah menikah dengan **DEVKI ADRIANSYAH** pada bulan Juni 2025;',
'Bahwa penghadap dan terampu merupakan anak dari pasangan **EDI NASRI** dan **YULNIATI**, yang perkawinannya telah berakhir karena perceraian berdasarkan Putusan Pengadilan Agama Pekanbaru Nomor 319/AC/2023/PA.Pbr tanggal {tgl:2023-03-15};',
'Bahwa setelah perceraian tersebut, **YULNIATI** (ibu kandung penghadap dan terampu) telah meninggal dunia pada tanggal {tgl:2026-01-27}, berdasarkan Kutipan Akta Kematian Nomor 1471-KM-11022026-0019 tanggal {tgl:2026-02-12} yang dikeluarkan oleh Kantor Pencatatan Sipil Kota Pekanbaru, sedangkan ayah kandung, **EDI NASRI**, masih hidup;',
'Bahwa penghadap mempunyai 4 (empat) orang saudara, di antaranya **ALVANY RAHMA YUDI**, **NURUL IZZATY**, dan terampu;',
'Bahwa terampu bernama **ALFARIQ SYUKRI YUDI**, NIK 1471061411020001, laki-laki, lahir di Pekanbaru pada tanggal {tgl:2003-11-14} ({usia:2003-11-14}) sebagaimana Kutipan Akta Kelahiran Nomor 148/TPP/2008 tanggal {tgl:2008-01-03} yang dikeluarkan Dinas Pendaftaran Penduduk Kota Pekanbaru, bertempat tinggal di alamat yang sama dengan penghadap;',
'Bahwa terampu telah dewasa, namun berkebutuhan khusus sejak lahir, mengalami gangguan sulit berbicara dan sering tantrum, tidak menamatkan Sekolah Dasar di Sekolah Luar Biasa (SLB), sebagaimana Surat Keterangan Dokter Nomor SKET/1/III/2026/RS.BHY tanggal {tgl:2026-03-11} dan Surat Keterangan Dokter (Jasmani) Nomor SKET/110/III/2026/RSBHY, sehingga tidak mampu mengurus dirinya sendiri maupun kepentingan hukumnya;',
'Bahwa terampu saat ini berada dalam pengasuhan dan tanggung jawab penghadap, dan seluruh kebutuhan hidupnya dipenuhi oleh penghadap;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk kepentingan hukum terampu, yaitu:',
'- Pengurusan pensiun atas nama almarhumah **YULNIATI** pada PT TASPEN, termasuk pengurusan administrasi, pengajuan klaim, penandatanganan dokumen, serta menerima dan mengurus hak-hak pensiun yang menjadi bagian terampu;',
'- Pengurusan hak-hak keperdataan atau keperluan hukum lainnya;',
'- Pengurusan administrasi dan/atau dokumen hukum lainnya;',
'Bahwa saudara kandung penghadap lainnya, **ALVANY RAHMA YUDI** dan **NURUL IZZATY**, telah memberikan kuasa kepada penghadap untuk mengajukan permohonan pengampuan tersebut;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **DIVA RAMADANI**, kerabat penghadap, menerangkan bahwa terampu adalah adik ketiga penghadap, ibu penghadap telah meninggal dunia sedangkan ayahnya masih hidup, serta terampu berkebutuhan khusus sejak lahir, sulit berbicara, sering tantrum, dan tidak tamat SD di SLB;',
'- Saksi **DEVKI ADRIANSYAH**, suami penghadap, memberikan keterangan yang bersesuaian mengenai keluarga penghadap dan kondisi terampu;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 155/Pdt.P/2026/PN Pbr tanggal {tgl:2026-04-24}, **ALFARIQ SYUKRI YUDI** ditetapkan sebagai orang yang tidak cakap hukum dan berada dalam pengasuhan serta tanggung jawab penghadap, dan penghadap diberi izin dan kewenangan untuk mewakili kepentingan hukum terampu, khususnya pengurusan pensiun almarhumah **YULNIATI** pada PT TASPEN serta pengurusan hak-hak keperdataan dan administrasi hukum lainnya;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'194/Pdt.P/2026/PN Pbr': [
'Bahwa penghadap bernama **LILI**, NIK 1471096209720023, perempuan, lahir di Padang pada tanggal {tgl:1972-09-22} ({usia:1972-09-22}), agama Kristen, pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Puri Nangka Indah Blok E No. 02, RT 001 RW 008, Kelurahan Tangkerang Barat, Kecamatan Marpoyan Damai, Kota Pekanbaru, Riau, adalah adik kandung dari terampu;',
'Bahwa penghadap tercatat dalam Kartu Keluarga Nomor 1471091512090009 atas nama **FERRY GUNAWAN** selaku kepala keluarga;',
'Bahwa penghadap dan terampu merupakan anak dari pasangan suami istri **MATIUS** dan **THERESIA ENG**, yang semasa hidupnya bertempat tinggal di Jalan Kamp Nias II No. 21 B Dalam, RT 001 RW 003, Kelurahan Belakang Pondok, Kecamatan Padang Selatan, Kota Padang, dan dari perkawinan tersebut dikaruniai 3 (tiga) orang anak, yaitu:',
'- **SINDRA** (almarhum), lahir di Padang pada tanggal {tgl:1970-03-02}, telah meninggal dunia berdasarkan Akta Kematian Nomor 1371-KM-08042022-0004;',
'- **SANDRA** (terampu), lahir di Padang pada tanggal {tgl:1971-09-10};',
'- **LILI** (penghadap), lahir di Padang pada tanggal {tgl:1972-09-22};',
'Bahwa kedua orang tua penghadap telah meninggal dunia, yaitu:',
'- **MATIUS** (ayah) meninggal dunia di Padang pada tanggal {tgl:2020-04-21}, berdasarkan Akta Kematian Nomor 1371-KM-08042022-0006 tanggal {tgl:2022-04-08} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Padang;',
'- **THERESIA ENG** (ibu) meninggal dunia di Padang pada tanggal {tgl:2010-04-27}, berdasarkan Akta Kematian Nomor 1371-KM-08042022-0005 tanggal {tgl:2022-04-08} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Padang;',
'Bahwa terampu bernama **SANDRA**, lahir di Padang pada tanggal {tgl:1971-09-10} ({usia:1971-09-10}), telah lama tinggal bersama penghadap di alamat tersebut di atas;',
'Bahwa terampu menderita penyakit Paranoid Schizophrenia sebagaimana Surat Rujukan RS Pekanbaru Medical Center Nomor 0069R0340426B000397 dan Resume Medis Rawat Jalan atas nama terampu, masih dalam kontrol rumah sakit karena kondisinya tidak stabil, harus minum obat 3 (tiga) kali sehari, dan tidak dapat melakukan kegiatan sehari-hari seperti makan dan mandi tanpa bantuan penghadap beserta suami dan anak-anaknya, sehingga terampu tidak cakap melakukan perbuatan hukum;',
'Bahwa harta kekayaan yang berkaitan dengan permohonan ini adalah:',
'- Sebidang tanah dan bangunan dengan Sertifikat Hak Milik NIB 05.01.000038607.0, terletak di Kelurahan Tirta Siak, Kecamatan Payung Sekaki, Kota Pekanbaru, Provinsi Riau, atas nama pemegang hak **SANDRA** dan **LILI**;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk memenuhi persyaratan penjualan tanah dan bangunan tersebut, karena pengobatan dan perawatan terampu memerlukan biaya yang cukup besar sementara kehidupan penghadap kurang mampu, sehingga Notaris dapat menerima kuasa dari penghadap untuk menjual tanpa menghadirkan dan tanpa tanda tangan terampu;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **ROSMAWATI IBRAHIM**, bibi penghadap, menerangkan bahwa kedua orang tua penghadap telah meninggal dunia dengan 3 (tiga) orang anak, terampu menderita Paranoid Schizophrenia yang memerlukan pengobatan rutin dan perawatan intensif, serta penghadap sangat perhatian merawat terampu yang telah lama tinggal bersamanya;',
'- Saksi **KODRATNO**, yang pernah bekerja memperbaiki rumah penghadap, menerangkan bahwa terampu tinggal bersama penghadap, menderita Paranoid Schizophrenia, dan penghadap bermaksud menjual tanah dan bangunan tersebut guna biaya pengobatan dan kebutuhan sehari-hari terampu;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 194/Pdt.P/2026/PN Pbr tanggal {tgl:2026-05-20}, penghadap selaku adik kandung telah ditetapkan sebagai Pengampu dari **SANDRA**, termasuk untuk menandatangani/memberikan kuasa menjual sebidang tanah dan bangunan tersebut di atas;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'309/Pdt.P/2026/PN Pbr': [
'Bahwa penghadap bernama **HERI NOFALIS**, NIK 1471122911600001, laki-laki, lahir di Bukittinggi pada tanggal {tgl:1960-11-29} ({usia:1960-11-29}), agama Islam, pekerjaan Karyawan Swasta, bertempat tinggal di Jalan Balai Pernikahan No. 23, RT 005 RW 002, Kelurahan Limbungan Baru, Kecamatan Rumbai, Kota Pekanbaru, Provinsi Riau, adalah paman kandung dari terampu;',
'Bahwa terampu bernama **HERU LASBERTI**, NIK 1375023004890001, laki-laki, lahir di Bukittinggi pada tanggal {tgl:1989-04-30} ({usia:1989-04-30}), bertempat tinggal di alamat yang sama dengan penghadap, adalah anak dari pasangan **RUSLAN** (almarhum) dan **LINDA AGUSTINA** (almarhumah) sebagaimana Surat Keterangan Lahir Nomor KET.KEL-40/RST/V/1989 tanggal {tgl:1989-05-02} yang dikeluarkan oleh Kepala Rumkit TK. IV Bukittinggi;',
'Bahwa **LINDA AGUSTINA**, ibu kandung terampu, adalah adik kandung penghadap;',
'Bahwa kedua orang tua terampu telah meninggal dunia, yaitu:',
'- **RUSLAN** (ayah) meninggal dunia ketika bertugas sebagai tentara di Timor Timur, pada saat terampu berumur 3 (tiga) bulan;',
'- **LINDA AGUSTINA** (ibu) meninggal dunia di Bukittinggi pada tanggal {tgl:2026-05-31}, berdasarkan Akta Kematian Nomor 1375-KM-24062026-0003 tanggal {tgl:2026-06-24} yang diterbitkan oleh Dinas Kependudukan Kota Bukittinggi, dan semasa hidupnya tidak pernah menikah lagi setelah suaminya meninggal dunia;',
'Bahwa terampu merupakan Anak Berkebutuhan Khusus (ABK)/penyandang disabilitas sejak lahir sebagaimana Surat Keterangan Dokter Pemeriksa pada UPT Puskesmas Rumbai, Dinas Kesehatan Kota Pekanbaru, tanggal {tgl:2026-07-07}, sehingga meskipun telah dewasa tidak mampu mengurus dirinya sendiri maupun kepentingan hukumnya;',
'Bahwa terampu saat ini berada dalam pengasuhan penghadap, dan selama ini seluruh biaya hidup terampu ditanggung oleh penghadap;',
'Bahwa almarhumah **LINDA AGUSTINA** meninggalkan harta peninggalan berupa sebuah rumah di Bukittinggi yang saat ini dalam keadaan kosong;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah agar penghadap dapat mengurus harta peninggalan almarhumah **LINDA AGUSTINA** serta mengantisipasi kemungkinan adanya hutang piutang almarhumah, dan untuk kepentingan hukum terampu, yaitu:',
'- Pengurusan administrasi dan/atau dokumen hukum;',
'- Pengurusan hak-hak keperdataan atau keperluan hukum lainnya;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **JONELSON**, sepupu penghadap, menerangkan bahwa ayah terampu meninggal dunia saat bertugas sebagai tentara di Timor Timur, ibu terampu tidak pernah menikah lagi dan meninggal dunia sekitar sebulan sebelum persidangan, terdapat harta peninggalan berupa rumah di Bukittinggi, serta selama ini terampu dibiayai oleh penghadap selaku pamannya;',
'- Saksi **FATMY**, sepupu penghadap, memberikan keterangan yang bersesuaian dan menambahkan bahwa ayah kandung terampu meninggal dunia ketika terampu berumur 3 (tiga) bulan;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 309/Pdt.P/2026/PN Pbr tanggal {tgl:2026-07-23}, **HERU LASBERTI** ditetapkan berada dalam pengasuhan dan tanggung jawab penghadap, dan penghadap diberi izin dan kewenangan untuk mewakili kepentingan hukum terampu, khususnya pengurusan administrasi dan/atau dokumen hukum serta hak-hak keperdataan terampu;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
};
