/* Isi BA Penghadapan yang disusun dari salinan penetapan (folder Drive "Daftar Penetapan Baru/Riau").
   Kunci = nomor penetapan. Baris: butir utama; "- " sub-butir; "-- " sub-sub-butir.
   {tgl:YYYY-MM-DD} dan {usia:YYYY-MM-DD} dihitung aplikasi (usia per tanggal sumpah). */
const BAP_SIAP_VERSI = 1;
const BAP_SIAP = {
'48/Pdt.P/2025/PN Pbr': [
'Bahwa penghadap bernama **JOANNA MURTHY REY**, lahir di Mentawai pada tanggal {tgl:1982-06-26} ({usia:1982-06-26}), agama Islam, pekerjaan Wiraswasta, bertempat tinggal di Komp. Wadya Graha I Blok O No. 8, RT 003 RW 007, Kelurahan Delima, Kecamatan Tampan, Kota Pekanbaru, Provinsi Riau, adalah anak kandung dari terampu;',
'Bahwa terampu bernama **BETTY UMAR**, lahir di Jakarta pada tanggal {tgl:1957-12-23} ({usia:1957-12-23}), adalah ibu kandung penghadap yang tinggal serumah dengan penghadap di alamat tersebut di atas;',
'Bahwa terampu mempunyai 4 (empat) orang anak, yaitu:',
'- **JEANIE AILANNA**, lahir di Pekanbaru pada tanggal {tgl:1980-06-27};',
'- **JOANNA MURTHY REY** (penghadap), lahir di Mentawai pada tanggal {tgl:1982-06-26};',
'- **INKA NAGARA**, lahir di Pekanbaru pada tanggal {tgl:1986-08-02};',
'- **IRYANDO DANOVAN**, lahir di Bukit Tinggi pada tanggal {tgl:1993-06-26};',
'Bahwa terampu menderita penyakit Possible Dementia Alzheimer disertai Hipertensi sebagaimana Surat Keterangan Dokter Rumah Sakit Umum Daerah Petala Bumi Nomor 445/RSUD-PB/4249, yang menyebabkan terampu sering lupa dengan kondisi yang semakin memburuk sesuai Catatan Perkembangan Pasien Terintegrasi (CPPT) rumah sakit tersebut, sehingga terampu tidak cakap melakukan perbuatan hukum;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk memenuhi persyaratan jual beli rumah milik terampu, karena rumah tersebut kondisinya kurang memadai dan terlalu besar untuk dihuni, sehingga hendak dijual untuk membeli rumah yang layak huni dan minimalis serta untuk biaya hidup dan pengobatan terampu;',
'Bahwa harta kekayaan milik terampu yang berkaitan dengan permohonan ini adalah sebagai berikut:',
'- Sebidang tanah dan bangunan dengan Sertifikat Hak Milik Nomor 793, terletak di Kelurahan Delima, Kecamatan Binawidya, Kota Pekanbaru, Provinsi Riau, atas nama **BETTY UMAR**;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 48/Pdt.P/2025/PN Pbr tanggal {tgl:2025-02-27}, penghadap telah ditetapkan sebagai Pengampu dari terampu **BETTY UMAR**, termasuk untuk menandatangani atau memberikan kuasa menjual sebidang tanah dan bangunan tersebut di atas;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'73/Pdt.P/2025/PN Pbr': [
'Bahwa penghadap bernama **MUSLIM MOHAMMAD**, lahir di Pekanbaru pada tanggal {tgl:1983-02-18} ({usia:1983-02-18}), agama Islam, pekerjaan Wiraswasta, bertempat tinggal di Jl. Inpres Gg. Gundaling, RT 003 RW 011, Kelurahan Perhentian Marpoyan Damai, Kecamatan Marpoyan Damai, Kota Pekanbaru, Provinsi Riau, adalah adik kandung dari terampu;',
'Bahwa penghadap dan terampu merupakan anak dari pasangan suami istri **JUSRI RAMLI** dan **RATNA JUWITA**, yang dari perkawinannya dikaruniai 4 (empat) orang anak, yaitu:',
'- **EBIET MOHAMMAD** (terampu), lahir di Pekanbaru pada tanggal {tgl:1979-12-22} ({usia:1979-12-22});',
'- **BONDAN MOHAMMAD**, lahir di Pekanbaru pada tanggal {tgl:1981-02-22};',
'- **MUSLIM MOHAMMAD** (penghadap), lahir di Pekanbaru pada tanggal {tgl:1983-02-18};',
'- **ANGGIA MURNI MOHAMMAD**, lahir di Pekanbaru pada tanggal {tgl:1984-11-16};',
'Bahwa kedua orang tua penghadap dan terampu telah meninggal dunia, yaitu:',
'- **JUSRI RAMLI** (ayah) meninggal dunia di Pekanbaru pada tanggal {tgl:2011-11-27}, berdasarkan Akta Kematian Nomor 1471-KM-11122014-0007 tanggal {tgl:2014-12-11} yang dikeluarkan oleh Dinas Kependudukan dan Pencatatan Sipil Kota Pekanbaru;',
'- **RATNA JUWITA** (ibu) meninggal dunia di Pekanbaru pada tanggal {tgl:2022-10-13}, berdasarkan Akta Kematian Nomor 1471-KM-03112022-0010 tanggal {tgl:2022-11-03} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru;',
'Bahwa terampu **EBIET MOHAMMAD** menderita gangguan kejiwaan sejak duduk di bangku SMP, pernah dirawat jalan di Rumah Sakit Jiwa Tampan sebagaimana Surat Keterangan Dirawat tanggal {tgl:2014-12-05} dan mengonsumsi obat Chlorpromazine, Trihexyphenidyl, dan Haloperidol sesuai Surat Keterangan Nomor 1914/PSBL/RH.02.02/9/2015;',
'Bahwa sejak ibu kandungnya meninggal dunia, terampu tidak lagi mengonsumsi obat tersebut, kondisinya menyerupai orang pikun, makan dan buang air di tempat, tidak dapat berkomunikasi maupun bersosialisasi dengan lingkungan, sering tertawa sendiri, dan dalam kesehariannya harus diawasi, sehingga tidak cakap melakukan perbuatan hukum;',
'Bahwa saat ini terampu tinggal bersama dan dirawat oleh penghadap;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk memenuhi persyaratan dokumen turun waris atas harta peninggalan almarhumah **RATNA JUWITA**, antara lain tanah dengan Sertifikat Hak Milik Nomor 04691, karena terampu tidak dapat bertindak sendiri akibat penyakit kejiwaan yang dideritanya;',
'Bahwa saudara kandung penghadap, **BONDAN MOHAMMAD** dan **ANGGIA MURNI MOHAMMAD**, telah memberikan kuasa kepada penghadap untuk mengurus penetapan pengampuan tersebut;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **LINDAWATI**, adik kandung ibu penghadap, menerangkan bahwa terampu menderita gangguan jiwa sejak SMP, kini tinggal bersama penghadap, tidak dapat berkomunikasi dan harus diawasi, serta bahwa almarhumah ibu penghadap memiliki harta warisan yang akan diurus turun warisnya;',
'- Saksi **ZUL ASRI**, Ketua RT di lingkungan tempat tinggal penghadap, menerangkan bahwa terampu menderita gangguan jiwa sejak SMP, tinggal bersama penghadap, dan tidak dapat berkomunikasi maupun bersosialisasi dengan lingkungan;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 73/Pdt.P/2025/PN Pbr tanggal {tgl:2025-03-20}, penghadap selaku saudara kandung telah ditetapkan sebagai Pengampu dari **EBIET MOHAMMAD** dan ditetapkan untuk bertindak melakukan penandatanganan/kuasa terhadap persyaratan turun waris;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'130/Pdt.P/2025/PN Pbr': [
'Bahwa penghadap bernama **YOLANDA OLIVIA AGNESIA S**, NIK 1403096110980010, perempuan, lahir di Duri pada tanggal {tgl:1998-10-21} ({usia:1998-10-21}), agama Katholik, pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Jl. Aur Kuning Perum Aur Kuning Blok K 1/2, RT 006 RW 003, Kelurahan Air Dingin, Kecamatan Bukit Raya, Kota Pekanbaru, adalah adik kandung dari terampu;',
'Bahwa penghadap telah menikah dengan **GUBTA PAUTAMA** sebagaimana Kutipan Akta Perkawinan, dan tercatat dalam Kartu Keluarga dengan **GUBTA PAUTAMA** selaku kepala keluarga;',
'Bahwa penghadap dan terampu merupakan anak dari pasangan suami istri yang sah **BILLIAN ANWAR HEDWIG. S** dan **LUSIA MARIA MAGDALENA. S**, yang semasa hidupnya bertempat tinggal di Komp. Merapi No. 9, RT 002 RW 003, Desa Pematang Pudu, Kecamatan Mandau, Kabupaten Bengkalis, Riau, dan dari perkawinan tersebut dikaruniai 3 (tiga) orang anak, yaitu:',
'- **PAULUS FELIX SITUMORANG** (terampu), lahir di Duri pada tanggal {tgl:1988-02-20};',
'- **YACOBUS NOVERIUS SITUMORANG**, lahir di Duri pada tanggal {tgl:1990-11-09};',
'- **YOLANDA OLIVIA AGNESIA S** (penghadap), lahir di Duri pada tanggal {tgl:1998-10-21};',
'Bahwa kedua orang tua penghadap telah meninggal dunia, yaitu:',
'- **BILLIAN ANWAR HEDWIG. S** (ayah) meninggal dunia di Pekanbaru pada tanggal {tgl:2021-01-17}, berdasarkan Akta Kematian Nomor 1471-KM-03022021-0011 yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru tanggal {tgl:2022-04-08};',
'- **LUSIA MARIA MAGDALENA. S** (ibu) meninggal dunia di Pekanbaru pada tanggal {tgl:2024-03-05}, berdasarkan Akta Kematian Nomor 1471-KM-15032024-0021 yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru tanggal {tgl:2024-04-29};',
'Bahwa dengan meninggalnya kedua orang tua tersebut, penghadap, terampu, dan **YACOBUS NOVERIUS SITUMORANG** merupakan ahli waris yang sah dari almarhum dan almarhumah;',
'Bahwa terampu bernama **PAULUS FELIX SITUMORANG**, NIK 1403092002880005, laki-laki, lahir di Duri pada tanggal {tgl:1988-02-20} ({usia:1988-02-20}), agama Katholik, tidak bekerja, beralamat KTP di Jl. Jayagiri No. 38, RT 01 RW 15, Kelurahan Jayagiri, Kecamatan Lembang, Kabupaten Bandung Barat, Jawa Barat, dan berdomisili di Jl. Karya Cipta No. B2, Kelurahan Air Dingin, Kecamatan Bukit Raya, Kota Pekanbaru, serta belum pernah menikah dan tidak mempunyai anak;',
'Bahwa terampu mengalami Autis atau Gangguan Spektrum Autisme (GSA) dan saat ini dirawat di Yayasan Pondok Anugerah Generasi Yosua sebagaimana Surat Keterangan Dirawat Nomor 001/SK/PAGY/V/2025 tanggal {tgl:2025-05-02}, karena kondisinya tidak stabil, harus dipantau setiap saat, dan wajib minum obat rutin 3 (tiga) kali sehari, sehingga terampu tidak cakap melakukan perbuatan hukum;',
'Bahwa semasa hidupnya orang tua penghadap meninggalkan harta warisan sebagai berikut:',
'- Sertifikat Hak Milik Nomor 6953, terletak di Perumahan Aur Kuning Blok K1 No. 2, Jalan Kaharuddin Nasution, Kelurahan Simpang Tiga (sekarang Kelurahan Air Dingin), Kecamatan Bukit Raya, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA. S**;',
'- Sertifikat Hak Milik Nomor 3879, terletak di Jalan Karya Cipta B2, Kelurahan Simpang Tiga (sekarang Kelurahan Air Dingin), Kecamatan Bukit Raya, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA SINAGA**;',
'- Sertifikat Hak Milik Nomor 4165, terletak di Jalan Karya 1 Gg. Pusri, Kelurahan Simpang Tiga (sekarang Kelurahan Air Dingin), Kecamatan Bukit Raya, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA SINAGA**;',
'- Sertifikat Hak Guna Bangunan Nomor 1255, terletak di Perumahan Sentosa Residence Blok D2 No. 3a, Jalan Abdul Malik, Kelurahan Sail, Kecamatan Tenayan Raya, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA SINAGA**;',
'- Sertifikat Hak Milik Nomor 569, terletak di Jalan Jenderal Sudirman, Kelurahan Babussalam, Kecamatan Mandau, Kabupaten Bengkalis, Riau, atas nama **LUSIA MARIA MAGDALENA. S**;',
'- Sertifikat Hak Pakai Nomor 00038, terletak di Jalan Pahlawan Kerja Gg. Matador II, Kelurahan Maharatu, Kecamatan Marpoyan Damai, Kota Pekanbaru, atas nama **LUSIA MARIA MAGDALENA. S**;',
'- Surat Ganti Kerugian Nomor 1.641/SGKT/V/2011, terletak di Kelurahan Balai Raja, Kecamatan Pinggir, Kabupaten Bengkalis, Riau, atas nama **LUSIA MARIA MAGDALENA SINAGA**;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk memenuhi persyaratan jual beli atas harta warisan tersebut, yang hasilnya akan digunakan untuk modal usaha, kebutuhan sehari-hari para ahli waris, serta biaya pengobatan terampu, sehingga Notaris/PPAT dapat menerima kuasa dari penghadap tanpa menghadirkan dan tanpa tanda tangan terampu;',
'Bahwa permohonan pengampuan tersebut telah mendapat persetujuan dari saudara kandung penghadap, **YACOBUS NOVERIUS SITUMORANG**, sebagaimana Surat Pernyataan Persetujuan tanggal {tgl:2025-05-02};',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **GUBTA PAUTAMA**, suami penghadap, menerangkan bahwa kedua orang tua penghadap telah meninggal dunia dengan meninggalkan harta warisan tersebut, bahwa terampu mengalami Autis (GSA), dirawat di Yayasan Pondok Anugerah Generasi Yosua, belum pernah menikah, serta tidak ada pihak yang keberatan atas permohonan ini;',
'- Saksi **R. RRO EVITA CITRADEWI**, ipar penghadap, memberikan keterangan yang bersesuaian mengenai ahli waris, harta warisan, kondisi terampu, dan persetujuan saudara kandung penghadap;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 130/Pdt.P/2025/PN Pbr tanggal {tgl:2025-05-14}, **PAULUS FELIX SITUMORANG** dinyatakan diletakkan di bawah pengampuan, dan penghadap selaku adik kandung ditetapkan sebagai Pengampu yang berhak bertindak untuk dan atas kepentingan hukum terampu, termasuk untuk menandatangani/memberikan kuasa menjual atas ketujuh bidang harta tersebut di atas;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'155/Pdt.P/2026/PN Pbr': [
'Bahwa penghadap bernama **AULIA RAHMA YUDI**, NIK 1471064306980021, perempuan, lahir di Pekanbaru pada tanggal {tgl:1998-06-03} ({usia:1998-06-03}), pekerjaan Wiraswasta, bertempat tinggal di Jl. Nelayan Gg. Sepat, RT 003 RW 010, Kelurahan Sri Meranti, Kecamatan Rumbai, Kota Pekanbaru, Provinsi Riau, adalah kakak kandung dari terampu;',
'Bahwa penghadap telah menikah dengan **DEVKI ADRIANSYAH** pada bulan Juni 2025;',
'Bahwa penghadap dan terampu merupakan anak dari pasangan **EDI NASRI** dan **YULNIATI**, yang perkawinannya telah berakhir karena perceraian berdasarkan Putusan Pengadilan Agama Pekanbaru Nomor 319/AC/2023/PA.Pbr tanggal {tgl:2023-03-15};',
'Bahwa setelah perceraian tersebut, **YULNIATI** (ibu kandung penghadap dan terampu) telah meninggal dunia pada tanggal {tgl:2026-01-27}, berdasarkan Kutipan Akta Kematian Nomor 1471-KM-11022026-0019 tanggal {tgl:2026-02-12} yang dikeluarkan oleh Kantor Pencatatan Sipil Kota Pekanbaru, sedangkan ayah kandung, **EDI NASRI**, masih hidup;',
'Bahwa penghadap mempunyai 4 (empat) orang saudara, di antaranya **ALVANY RAHMA YUDI**, **NURUL IZZATY**, dan terampu;',
'Bahwa terampu bernama **ALFARIQ SYUKRI YUDI**, NIK 1471061411020001, laki-laki, lahir di Pekanbaru pada tanggal {tgl:2003-11-14} ({usia:2003-11-14}) sebagaimana Kutipan Akta Kelahiran Nomor 148/TPP/2008 tanggal {tgl:2008-01-03} yang dikeluarkan Dinas Pendaftaran Penduduk Kota Pekanbaru, bertempat tinggal di alamat yang sama dengan penghadap;',
'Bahwa terampu telah dewasa, namun berkebutuhan khusus sejak lahir, mengalami gangguan sulit berbicara dan sering tantrum, tidak menamatkan Sekolah Dasar di Sekolah Luar Biasa (SLB), sebagaimana Surat Keterangan Dokter Nomor SKET/1/III/2026/RS.BHY tanggal {tgl:2026-03-11} dan Surat Keterangan Dokter (Jasmani) Nomor SKET/110/III/2026/RSBHY, sehingga tidak mampu mengurus dirinya sendiri maupun kepentingan hukumnya;',
'Bahwa terampu saat ini berada dalam pengasuhan dan tanggung jawab penghadap, dan seluruh kebutuhan hidupnya dipenuhi oleh penghadap;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk kepentingan hukum terampu, yaitu:',
'- Pengurusan pensiun atas nama almarhumah **YULNIATI** pada PT TASPEN, termasuk pengurusan administrasi, pengajuan klaim, penandatanganan dokumen, serta menerima dan mengurus hak-hak pensiun yang menjadi bagian terampu;',
'- Pengurusan hak-hak keperdataan atau keperluan hukum lainnya;',
'- Pengurusan administrasi dan/atau dokumen hukum lainnya;',
'Bahwa saudara kandung penghadap lainnya, **ALVANY RAHMA YUDI** dan **NURUL IZZATY**, telah memberikan kuasa kepada penghadap untuk mengajukan permohonan pengampuan tersebut;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **DIVA RAMADANI**, kerabat penghadap, menerangkan bahwa terampu adalah adik ketiga penghadap, ibu penghadap telah meninggal dunia sedangkan ayahnya masih hidup, serta terampu berkebutuhan khusus sejak lahir, sulit berbicara, sering tantrum, dan tidak tamat SD di SLB;',
'- Saksi **DEVKI ADRIANSYAH**, suami penghadap, memberikan keterangan yang bersesuaian mengenai keluarga penghadap dan kondisi terampu;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 155/Pdt.P/2026/PN Pbr tanggal {tgl:2026-04-24}, **ALFARIQ SYUKRI YUDI** ditetapkan sebagai orang yang tidak cakap hukum dan berada dalam pengasuhan serta tanggung jawab penghadap, dan penghadap diberi izin dan kewenangan untuk mewakili kepentingan hukum terampu, khususnya pengurusan pensiun almarhumah **YULNIATI** pada PT TASPEN serta pengurusan hak-hak keperdataan dan administrasi hukum lainnya;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'194/Pdt.P/2026/PN Pbr': [
'Bahwa penghadap bernama **LILI**, NIK 1471096209720023, perempuan, lahir di Padang pada tanggal {tgl:1972-09-22} ({usia:1972-09-22}), agama Kristen, pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Puri Nangka Indah Blok E No. 02, RT 001 RW 008, Kelurahan Tangkerang Barat, Kecamatan Marpoyan Damai, Kota Pekanbaru, Riau, adalah adik kandung dari terampu;',
'Bahwa penghadap tercatat dalam Kartu Keluarga Nomor 1471091512090009 atas nama **FERRY GUNAWAN** selaku kepala keluarga;',
'Bahwa penghadap dan terampu merupakan anak dari pasangan suami istri **MATIUS** dan **THERESIA ENG**, yang semasa hidupnya bertempat tinggal di Jalan Kamp Nias II No. 21 B Dalam, RT 001 RW 003, Kelurahan Belakang Pondok, Kecamatan Padang Selatan, Kota Padang, dan dari perkawinan tersebut dikaruniai 3 (tiga) orang anak, yaitu:',
'- **SINDRA** (almarhum), lahir di Padang pada tanggal {tgl:1970-03-02}, telah meninggal dunia berdasarkan Akta Kematian Nomor 1371-KM-08042022-0004;',
'- **SANDRA** (terampu), lahir di Padang pada tanggal {tgl:1971-09-10};',
'- **LILI** (penghadap), lahir di Padang pada tanggal {tgl:1972-09-22};',
'Bahwa kedua orang tua penghadap telah meninggal dunia, yaitu:',
'- **MATIUS** (ayah) meninggal dunia di Padang pada tanggal {tgl:2020-04-21}, berdasarkan Akta Kematian Nomor 1371-KM-08042022-0006 tanggal {tgl:2022-04-08} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Padang;',
'- **THERESIA ENG** (ibu) meninggal dunia di Padang pada tanggal {tgl:2010-04-27}, berdasarkan Akta Kematian Nomor 1371-KM-08042022-0005 tanggal {tgl:2022-04-08} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Padang;',
'Bahwa terampu bernama **SANDRA**, lahir di Padang pada tanggal {tgl:1971-09-10} ({usia:1971-09-10}), telah lama tinggal bersama penghadap di alamat tersebut di atas;',
'Bahwa terampu menderita penyakit Paranoid Schizophrenia sebagaimana Surat Rujukan RS Pekanbaru Medical Center Nomor 0069R0340426B000397 dan Resume Medis Rawat Jalan atas nama terampu, masih dalam kontrol rumah sakit karena kondisinya tidak stabil, harus minum obat 3 (tiga) kali sehari, dan tidak dapat melakukan kegiatan sehari-hari seperti makan dan mandi tanpa bantuan penghadap beserta suami dan anak-anaknya, sehingga terampu tidak cakap melakukan perbuatan hukum;',
'Bahwa harta kekayaan yang berkaitan dengan permohonan ini adalah:',
'- Sebidang tanah dan bangunan dengan Sertifikat Hak Milik NIB 05.01.000038607.0, terletak di Kelurahan Tirta Siak, Kecamatan Payung Sekaki, Kota Pekanbaru, Provinsi Riau, atas nama pemegang hak **SANDRA** dan **LILI**;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah untuk memenuhi persyaratan penjualan tanah dan bangunan tersebut, karena pengobatan dan perawatan terampu memerlukan biaya yang cukup besar sementara kehidupan penghadap kurang mampu, sehingga Notaris dapat menerima kuasa dari penghadap untuk menjual tanpa menghadirkan dan tanpa tanda tangan terampu;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **ROSMAWATI IBRAHIM**, bibi penghadap, menerangkan bahwa kedua orang tua penghadap telah meninggal dunia dengan 3 (tiga) orang anak, terampu menderita Paranoid Schizophrenia yang memerlukan pengobatan rutin dan perawatan intensif, serta penghadap sangat perhatian merawat terampu yang telah lama tinggal bersamanya;',
'- Saksi **KODRATNO**, yang pernah bekerja memperbaiki rumah penghadap, menerangkan bahwa terampu tinggal bersama penghadap, menderita Paranoid Schizophrenia, dan penghadap bermaksud menjual tanah dan bangunan tersebut guna biaya pengobatan dan kebutuhan sehari-hari terampu;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 194/Pdt.P/2026/PN Pbr tanggal {tgl:2026-05-20}, penghadap selaku adik kandung telah ditetapkan sebagai Pengampu dari **SANDRA**, termasuk untuk menandatangani/memberikan kuasa menjual sebidang tanah dan bangunan tersebut di atas;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'309/Pdt.P/2026/PN Pbr': [
'Bahwa penghadap bernama **HERI NOFALIS**, NIK 1471122911600001, laki-laki, lahir di Bukittinggi pada tanggal {tgl:1960-11-29} ({usia:1960-11-29}), agama Islam, pekerjaan Karyawan Swasta, bertempat tinggal di Jalan Balai Pernikahan No. 23, RT 005 RW 002, Kelurahan Limbungan Baru, Kecamatan Rumbai, Kota Pekanbaru, Provinsi Riau, adalah paman kandung dari terampu;',
'Bahwa terampu bernama **HERU LASBERTI**, NIK 1375023004890001, laki-laki, lahir di Bukittinggi pada tanggal {tgl:1989-04-30} ({usia:1989-04-30}), bertempat tinggal di alamat yang sama dengan penghadap, adalah anak dari pasangan **RUSLAN** (almarhum) dan **LINDA AGUSTINA** (almarhumah) sebagaimana Surat Keterangan Lahir Nomor KET.KEL-40/RST/V/1989 tanggal {tgl:1989-05-02} yang dikeluarkan oleh Kepala Rumkit TK. IV Bukittinggi;',
'Bahwa **LINDA AGUSTINA**, ibu kandung terampu, adalah adik kandung penghadap;',
'Bahwa kedua orang tua terampu telah meninggal dunia, yaitu:',
'- **RUSLAN** (ayah) meninggal dunia ketika bertugas sebagai tentara di Timor Timur, pada saat terampu berumur 3 (tiga) bulan;',
'- **LINDA AGUSTINA** (ibu) meninggal dunia di Bukittinggi pada tanggal {tgl:2026-05-31}, berdasarkan Akta Kematian Nomor 1375-KM-24062026-0003 tanggal {tgl:2026-06-24} yang diterbitkan oleh Dinas Kependudukan Kota Bukittinggi, dan semasa hidupnya tidak pernah menikah lagi setelah suaminya meninggal dunia;',
'Bahwa terampu merupakan Anak Berkebutuhan Khusus (ABK)/penyandang disabilitas sejak lahir sebagaimana Surat Keterangan Dokter Pemeriksa pada UPT Puskesmas Rumbai, Dinas Kesehatan Kota Pekanbaru, tanggal {tgl:2026-07-07}, sehingga meskipun telah dewasa tidak mampu mengurus dirinya sendiri maupun kepentingan hukumnya;',
'Bahwa terampu saat ini berada dalam pengasuhan penghadap, dan selama ini seluruh biaya hidup terampu ditanggung oleh penghadap;',
'Bahwa almarhumah **LINDA AGUSTINA** meninggalkan harta peninggalan berupa sebuah rumah di Bukittinggi yang saat ini dalam keadaan kosong;',
'Bahwa maksud penghadap mengajukan permohonan pengampuan adalah agar penghadap dapat mengurus harta peninggalan almarhumah **LINDA AGUSTINA** serta mengantisipasi kemungkinan adanya hutang piutang almarhumah, dan untuk kepentingan hukum terampu, yaitu:',
'- Pengurusan administrasi dan/atau dokumen hukum;',
'- Pengurusan hak-hak keperdataan atau keperluan hukum lainnya;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **JONELSON**, sepupu penghadap, menerangkan bahwa ayah terampu meninggal dunia saat bertugas sebagai tentara di Timor Timur, ibu terampu tidak pernah menikah lagi dan meninggal dunia sekitar sebulan sebelum persidangan, terdapat harta peninggalan berupa rumah di Bukittinggi, serta selama ini terampu dibiayai oleh penghadap selaku pamannya;',
'- Saksi **FATMY**, sepupu penghadap, memberikan keterangan yang bersesuaian dan menambahkan bahwa ayah kandung terampu meninggal dunia ketika terampu berumur 3 (tiga) bulan;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Pekanbaru Nomor 309/Pdt.P/2026/PN Pbr tanggal {tgl:2026-07-23}, **HERU LASBERTI** ditetapkan berada dalam pengasuhan dan tanggung jawab penghadap, dan penghadap diberi izin dan kewenangan untuk mewakili kepentingan hukum terampu, khususnya pengurusan administrasi dan/atau dokumen hukum serta hak-hak keperdataan terampu;',
'Bahwa penghadap sanggup menjalankan kewajiban sebagai Pengampu dengan penuh tanggung jawab sesuai peraturan perundang-undangan, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Pengampu Pengawas.'
],
'332/Pdt.P/2025/PA.Pbr': [
'Bahwa penghadap bernama **JUNITA WULANDARI BINTI AFRIJON**, NIK 3202295406910012, perempuan, lahir di Bandung pada tanggal {tgl:1995-12-14} ({usia:1995-12-14}), agama Islam, pendidikan SLTP, pekerjaan Ibu Rumah Tangga, bertempat tinggal di Jalan Bina Krida RT 001 RW 003, Kelurahan Simpang Baru, Kecamatan Bina Widya, Kota Pekanbaru, adalah ibu kandung dari anak yang dimohonkan perwalian;',
'Bahwa penghadap telah melangsungkan perkawinan dengan **ANDES SAPUTRA BIN SYAFARUDDIN** pada tanggal {tgl:2011-07-18}, yang dicatat oleh Pegawai Pencatat Nikah Kantor Urusan Agama Kecamatan Cibeunying Kidul, Kota Bandung, Jawa Barat, sebagaimana Kutipan Akta Nikah Nomor 561/86/VII/2011 tanggal {tgl:2011-07-18};',
'Bahwa dari perkawinan tersebut penghadap dikaruniai 1 (satu) orang anak, yaitu **MUHAMMAD DELAN SAPUTRA**, laki-laki, lahir di Sukabumi pada tanggal {tgl:2012-05-14} ({usia:2012-05-14}), sebagaimana Akta Kelahiran Nomor 3202-LT-25102012-0068 tanggal {tgl:2012-10-25} yang dikeluarkan oleh Dinas Kependudukan dan Pencatatan Sipil Kabupaten Sukabumi;',
'Bahwa suami penghadap, **ANDES SAPUTRA BIN SYAFARUDDIN**, telah meninggal dunia di Batusangkar pada tanggal {tgl:2022-03-21} karena sakit stroke dalam keadaan beragama Islam, sebagaimana Kutipan Akta Kematian Nomor 3202-KM-19042022-0037 tanggal {tgl:2022-04-19} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kabupaten Sukabumi;',
'Bahwa sejak meninggalnya ayah kandungnya, anak tersebut diasuh dan dipelihara oleh penghadap sebagai satu-satunya orang tua yang masih hidup dan orang terdekat dengan anak;',
'Bahwa anak yang masih di bawah umur (belum mencapai umur 18 tahun dan belum pernah kawin) dan berada di bawah perwalian penghadap adalah **MUHAMMAD DELAN SAPUTRA**, lahir tanggal {tgl:2012-05-14} ({usia:2012-05-14}), yang belum bekerja dan belum cakap melakukan perbuatan hukum;',
'Bahwa harta kekayaan milik anak di bawah umur tersebut yang berkaitan dengan permohonan ini adalah:',
'- Sebidang tanah dengan Sertifikat Hak Milik Nomor 596, terletak di Desa Sukamantri, Kecamatan Cisaat, Kabupaten Sukabumi, Provinsi Jawa Barat, atas nama anak **MUHAMMAD DELAN SAPUTRA**;',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah dalam rangka pengurusan balik nama Sertifikat Hak Milik Nomor 596 tersebut serta untuk kepentingan administrasi lainnya yang memerlukan tindakan hukum atas nama anak;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **HERLINA BINTI SYAIR ALAMSYAH**, bibi penghadap, menerangkan bahwa dari perkawinan penghadap dengan almarhum **ANDES SAPUTRA** dikaruniai 1 (satu) orang anak yang kini berumur 13 tahun, ayah kandung anak meninggal dunia pada tanggal {tgl:2022-03-21} karena sakit stroke, dan sejak itu anak diasuh serta dipelihara oleh penghadap;',
'- Saksi **ANGELINA PUTRI BINTI HENDRA**, sepupu penghadap, memberikan keterangan yang bersesuaian dan menerangkan bahwa penghadap adalah satu-satunya orang terdekat dengan anak tersebut;',
'Bahwa berdasarkan Penetapan Pengadilan Agama Pekanbaru Nomor 332/Pdt.P/2025/PA.Pbr tanggal {tgl:2026-01-22}, penghadap telah ditetapkan sebagai **Wali** dari anak bernama **MUHAMMAD DELAN SAPUTRA** untuk mewakili dan melakukan segala tindakan hukum bagi dan atas nama anak tersebut sepanjang berkaitan dengan kepentingannya;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'126/Pdt.P/2026/PA.Pbr': [
'Bahwa penghadap bernama **NURHAYATI BINTI ZAKARIA**, NIK 1409024711730001, perempuan, lahir di Pekanbaru pada tanggal {tgl:1973-11-07} ({usia:1973-11-07}), agama Islam, pendidikan terakhir SLTA, pekerjaan Ibu Rumah Tangga, bertempat tinggal di Jalan Kaharuddin Nasution Nomor 178, RT 005 RW 006, Kelurahan Maharatu, Kecamatan Marpoyan Damai, Kota Pekanbaru, Provinsi Riau, adalah bibi kandung (kakak kandung dari ayah kandung) anak yang dimohonkan perwalian;',
'Bahwa penghadap telah menikah dengan **IRPANSYAH** sebagaimana Kutipan Akta Nikah Nomor 906/121/XI/1999 tanggal {tgl:1999-11-26} yang dikeluarkan oleh Pegawai Pencatat Nikah Kecamatan Bukit Raya, dan suami penghadap telah menyatakan mengetahui, menyetujui, serta tidak keberatan penghadap ditetapkan sebagai wali;',
'Bahwa anak yang dimohonkan perwalian adalah anak kandung dari pasangan suami istri **MUHAMMAD YUSUF BIN ZAKARIA** (adik kandung penghadap) dan **SRI WAHYU NINGSIH BINTI H. ABDUL SALAM EFENDI**, yang menikah pada tanggal {tgl:2009-12-20} sebagaimana Kutipan Akta Nikah Nomor 595/66/XII/2009;',
'Bahwa dari perkawinan tersebut lahir 1 (satu) orang anak, yaitu **SYAFIRA RAMADHANI BINTI MUHAMMAD YUSUF**, perempuan, lahir di Pekanbaru pada tanggal {tgl:2010-08-20} ({usia:2010-08-20}), sebagaimana Akta Kelahiran Nomor 1471-LT-08092014-0166;',
'Bahwa kedua orang tua kandung anak tersebut telah meninggal dunia karena sakit, yaitu:',
'- **SRI WAHYU NINGSIH BINTI H. ABDUL SALAM EFENDI** (ibu kandung) meninggal dunia di Pekanbaru pada tanggal {tgl:2013-12-22}, berdasarkan Akta Kematian Nomor 1471-KM-06012016-0011 tanggal {tgl:2016-01-06} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru;',
'- **MUHAMMAD YUSUF BIN ZAKARIA** (ayah kandung) meninggal dunia di Pekanbaru pada tanggal {tgl:2017-01-12}, berdasarkan Akta Kematian Nomor 1471-KM-22092022-0006 tanggal {tgl:2022-09-22} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru;',
'Bahwa sejak kedua orang tuanya meninggal dunia, anak tersebut tinggal bersama serta diasuh, dipelihara, dan dipenuhi kebutuhan hidup serta pendidikannya oleh penghadap, dan tidak ada keberatan dari pihak keluarga lainnya;',
'Bahwa anak yang masih di bawah umur (belum mencapai umur 18 tahun dan belum pernah kawin) dan berada di bawah perwalian penghadap adalah **SYAFIRA RAMADHANI BINTI MUHAMMAD YUSUF**, lahir tanggal {tgl:2010-08-20} ({usia:2010-08-20}), yang belum bekerja dan belum cakap melakukan perbuatan hukum;',
'Bahwa harta kekayaan yang menjadi hak anak di bawah umur tersebut sebagai ahli waris almarhum ayah kandungnya adalah:',
'- Sebidang tanah yang di atasnya berdiri bangunan ruko dengan Sertifikat Hak Milik Nomor 1685, terletak di Kelurahan Maharatu, Kecamatan Marpoyan Damai, Kota Pekanbaru, atas nama almarhum **MUHAMMAD YUSUF BIN ZAKARIA**;',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah untuk mewakili anak dalam pengurusan Penetapan Ahli Waris atas nama almarhum **MUHAMMAD YUSUF BIN ZAKARIA** serta melakukan tindakan hukum berupa penjualan sebidang tanah berikut bangunan ruko tersebut, sepanjang dilakukan demi kepentingan anak;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **ULYA BIN PI\'I**, sepupu penghadap, menerangkan bahwa kedua orang tua anak telah meninggal dunia karena sakit, anak kini berumur 15 tahun dan diasuh oleh penghadap sebagai bibinya dan satu-satunya orang terdekat, serta permohonan diajukan untuk penjualan tanah dan ruko di Kelurahan Maharatu;',
'- Saksi **M. FRENGKI JOHAN BIN BUHIYAR**, keponakan penghadap, memberikan keterangan yang bersesuaian dengan saksi pertama;',
'Bahwa berdasarkan Penetapan Pengadilan Agama Pekanbaru Nomor 126/Pdt.P/2026/PA.Pbr tanggal {tgl:2026-07-06}, penghadap telah ditetapkan sebagai **Wali** yang sah dari anak **SYAFIRA RAMADHANI BINTI MUHAMMAD YUSUF**, dan berwenang mewakili anak tersebut di dalam dan di luar pengadilan, termasuk pengurusan Penetapan Ahli Waris almarhum **MUHAMMAD YUSUF BIN ZAKARIA** dan penjualan sebidang tanah berikut bangunan ruko dengan Sertifikat Hak Milik Nomor 1685;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, dengan iktikad baik dan transparan, mengurus kepentingan dan harta kekayaan anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'133/Pdt.P/2026/PA.Pbr': [
'Bahwa penghadap bernama **NURMADINIS BINTI KAMEK**, perempuan, lahir di Limpato pada tanggal {tgl:1980-09-06} ({usia:1980-09-06}), agama Islam, pendidikan SLTA, pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Jl. Bintara No. 10B, RT 005 RW 012, Kelurahan Labuh Baru Timur, Kecamatan Payung Sekaki, Kota Pekanbaru, Riau, adalah ibu kandung dari anak yang dimohonkan perwalian;',
'Bahwa penghadap telah melangsungkan perkawinan dengan **RAPIK BIN GOMBA** sebagaimana Kutipan Akta Nikah Nomor 520/28/VIII/2003 yang dikeluarkan oleh Kantor Urusan Agama Kecamatan VII Koto, Kabupaten Padang Pariaman, Sumatera Barat, dan semasa hidupnya **RAPIK BIN GOMBA** bekerja sebagai petani serta hanya menikah dengan penghadap;',
'Bahwa dari perkawinan tersebut penghadap dikaruniai 1 (satu) orang anak laki-laki, yaitu **MUHAMMAD FAISAL ARAQI BIN RAPIK**, lahir di Pekanbaru pada tanggal {tgl:2011-11-16} ({usia:2011-11-16}), sebagaimana Kutipan Akta Kelahiran Nomor 1471-LU-19122011-0014 tanggal {tgl:2011-12-19} yang dikeluarkan oleh Dinas Kependudukan dan Pencatatan Sipil Kota Pekanbaru;',
'Bahwa suami penghadap, **RAPIK BIN GOMBA**, telah meninggal dunia di Pekanbaru pada tanggal {tgl:2020-03-20} dalam keadaan beragama Islam, murni karena sakit ketika dalam masa perawatan di RSU Santa Maria Pekanbaru, dan dimakamkan di Tempat Pemakaman Umum Sigunggung, Payung Sekaki, Kota Pekanbaru, sebagaimana Kutipan Akta Kematian Nomor 1471-KM-07042020-0010 tanggal {tgl:2020-04-08} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru;',
'Bahwa sejak ayahnya meninggal dunia, anak tersebut tinggal dan diasuh oleh penghadap dalam keadaan sehat dengan tumbuh kembang yang baik, sedangkan penghadap tidak bekerja dan mengelola keuangan dari harta peninggalan almarhum suaminya;',
'Bahwa anak yang masih di bawah umur (belum mencapai umur 18 tahun dan belum pernah kawin) dan berada di bawah perwalian penghadap adalah **MUHAMMAD FAISAL ARAQI BIN RAPIK**, lahir tanggal {tgl:2011-11-16} ({usia:2011-11-16}), yang belum cakap melakukan perbuatan hukum;',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah untuk mengurus, memudahkan, dan mempercepat pengurusan surat-menyurat serta penandatanganan dokumen terkait harta peninggalan almarhum **RAPIK BIN GOMBA**, mewakili anak sebagai ahli waris almarhum dalam perbuatan hukum, dan menggunakan hasil pengelolaan harta tersebut untuk memenuhi kebutuhan hidup serta biaya pendidikan anak;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **SRI REZEKI BINTI SUTOMO**, tetangga penghadap, menerangkan bahwa **RAPIK BIN GOMBA** meninggal dunia pada tanggal {tgl:2020-03-20} murni karena sakit tanpa unsur penganiayaan, anak diasuh oleh penghadap dalam kondisi sehat, serta penghadap berakhlak baik, jujur, adil, tidak boros, tidak pernah dihukum, dan mampu mengasuh anaknya;',
'- Saksi **INDRAWATI BINTI JANIR**, tetangga penghadap, memberikan keterangan yang bersesuaian dan menerangkan bahwa jenazah almarhum diselenggarakan secara syariat Islam dan dimakamkan di pekuburan muslim;',
'Bahwa berdasarkan Penetapan Pengadilan Agama Pekanbaru Nomor 133/Pdt.P/2026/PA.Pbr tanggal {tgl:2026-06-25}, penghadap telah ditetapkan sebagai **Wali** dari anak kandungnya **MUHAMMAD FAISAL ARAQI BIN RAPIK** yang dapat bertindak secara hukum melakukan segala perbuatan atau tindakan hukum bagi anak tersebut, baik di dalam maupun di luar pengadilan;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'74/Pdt.P/2026/PA.Pbr': [
'Bahwa penghadap bernama **ROSMALA DEWI BINTI YAKUB**, NIK 1471024908770001, perempuan, lahir di Binjai Serbangan pada tanggal {tgl:1995-04-03} ({usia:1995-04-03}), agama Islam, pendidikan D III, pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Jalan A. Yani Gang Sardino No. 16A, RT 003 RW 002, Kelurahan Tanah Datar, Kecamatan Pekanbaru Kota, Kota Pekanbaru, Provinsi Riau, adalah ibu kandung dari anak-anak yang dimohonkan perwalian;',
'Bahwa penghadap telah melangsungkan perkawinan dengan **SUGIYANTO BIN B. GIMUN S.** pada tanggal {tgl:2004-09-11} sebagaimana Kutipan Akta Nikah Nomor 222/07/IX/2004 yang dikeluarkan oleh Kantor Urusan Agama Kecamatan Pekanbaru Kota, dan semasa hidupnya almarhum hanya menikah dengan penghadap;',
'Bahwa dari perkawinan tersebut penghadap dikaruniai 3 (tiga) orang anak, yaitu:',
'- **MUHAMMAD FARIS AULIA BIN SUGIYANTO**, laki-laki, lahir pada tanggal {tgl:2005-11-08} ({usia:2005-11-08}), telah dewasa;',
'- **MUHAMMAD BAIHAQI BIN SUGIYANTO**, laki-laki, lahir pada tanggal {tgl:2009-07-12} ({usia:2009-07-12}), sebagaimana Akta Kelahiran Nomor 3896/TTP/2009 tanggal {tgl:2009-08-14};',
'- **AISHA NAADHIRA MAHREEN BINTI SUGIYANTO**, perempuan, lahir di Pekanbaru pada tanggal {tgl:2020-04-01} ({usia:2020-04-01}), sebagaimana Kutipan Akta Kelahiran Nomor 1471-LT-21072020-0002 tanggal {tgl:2020-07-21};',
'Bahwa suami penghadap, **SUGIYANTO BIN B. GIMUN S.**, telah meninggal dunia di Pekanbaru pada tanggal {tgl:2024-10-10} dalam keadaan beragama Islam, murni karena sakit tanpa unsur penganiayaan, sebagaimana Kutipan Akta Kematian Nomor 1471-KM-16102024-0001 tanggal {tgl:2024-10-17} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Pekanbaru;',
'Bahwa sejak ayahnya meninggal dunia, anak-anak tinggal dan diasuh oleh penghadap dalam kondisi sehat dengan tumbuh kembang yang baik, sedangkan penghadap tidak bekerja dan mengelola keuangan dari harta peninggalan almarhum suaminya;',
'Bahwa dari anak-anak tersebut, yang masih di bawah umur (belum mencapai umur 18 tahun dan belum pernah kawin) dan berada di bawah perwalian penghadap adalah 2 (dua) orang, yaitu:',
'- **MUHAMMAD BAIHAQI BIN SUGIYANTO**, laki-laki, lahir tanggal {tgl:2009-07-12} ({usia:2009-07-12});',
'- **AISHA NAADHIRA MAHREEN BINTI SUGIYANTO**, perempuan, lahir tanggal {tgl:2020-04-01} ({usia:2020-04-01});',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah untuk mengurus balik nama surat tanah peninggalan almarhum serta mengurus administrasi pinjaman Kredit Usaha Rakyat (KUR) pada bank, yang akan digunakan sebagai modal usaha guna memenuhi kebutuhan hidup dan biaya pendidikan anak-anak, serta untuk keperluan administrasi lainnya;',
'Bahwa para ahli waris almarhum telah menyetujui dan memberikan kuasa kepada penghadap untuk mengurus perwalian tersebut sebagaimana Surat Pernyataan Ahli Waris, Silsilah Ahli Waris, dan Surat Kuasa Ahli Waris;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **YOSI SARTIKA BINTI ACHMAD**, sepupu penghadap, menerangkan bahwa almarhum **SUGIYANTO** meninggal dunia pada tanggal {tgl:2024-10-10} karena sakit, anak-anak diasuh oleh penghadap dalam kondisi sehat, penghadap berakhlak baik, jujur, adil, dan tidak boros, serta permohonan diajukan untuk mengurus pinjaman KUR guna modal usaha dan biaya pendidikan anak;',
'- Saksi **JON HENDRIK BIN YAKUB**, saudara kandung penghadap, memberikan keterangan yang bersesuaian dengan saksi pertama;',
'Bahwa berdasarkan Penetapan Pengadilan Agama Pekanbaru Nomor 74/Pdt.P/2026/PA.Pbr tanggal {tgl:2026-04-28}, penghadap telah ditetapkan sebagai **Wali** dari anak-anaknya **MUHAMMAD BAIHAQI** dan **AISHA NAADHIRA MAHREEN**;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak-anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'111/Pdt.P/2026/PA.Pbr': [
'Bahwa penghadap bernama **DIAR SESMA BINTI DAHLAN**, NIK 1471095107710041, perempuan, lahir di Lubuk Basung pada tanggal {tgl:1971-07-11} ({usia:1971-07-11}), agama Islam, pendidikan SLTP, pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Jalan Kayu Manis Gang Seminai, RT 002 RW 008, Kelurahan Sidomulyo Timur, Kecamatan Marpoyan Damai, Kota Pekanbaru, adalah ibu kandung dari anak yang dimohonkan perwalian;',
'Bahwa penghadap telah melangsungkan perkawinan dengan **IRMAN BIN BUYUANG BAGINDO SUTAN** pada tanggal {tgl:1989-05-12} sebagaimana Kutipan Akta Nikah Nomor 20/6/V/1989 yang dikeluarkan oleh Kantor Urusan Agama Kecamatan Salimpaung, Kabupaten Tanah Datar;',
'Bahwa dari perkawinan tersebut penghadap dikaruniai 6 (enam) orang anak, yaitu:',
'- **YESSI IRMA**, lahir pada tanggal {tgl:1990-01-23} ({usia:1990-01-23}), telah dewasa;',
'- **RAHMAT MULIA**, lahir pada tanggal {tgl:1993-03-17} ({usia:1993-03-17}), telah dewasa;',
'- **RAHMITA SARI**, lahir pada tanggal {tgl:1996-01-15} ({usia:1996-01-15}), telah dewasa;',
'- **RENDI OKMA MULIA**, lahir pada tanggal {tgl:1998-10-03} ({usia:1998-10-03}), telah dewasa;',
'- **NADIA PUTRI**, lahir pada tanggal {tgl:2002-06-03} ({usia:2002-06-03}), telah dewasa;',
'- **HAFIZ RABBANI MULIA**, laki-laki, lahir pada tanggal {tgl:2011-09-07} ({usia:2011-09-07}), sebagaimana Kutipan Akta Kelahiran Nomor 1471-LU-11102011-0070 tanggal {tgl:2011-10-11};',
'Bahwa suami penghadap, **IRMAN BIN BUYUANG BAGINDO SUTAN**, telah meninggal dunia di Pekanbaru pada tanggal {tgl:2023-11-26} karena sakit, sebagaimana Kutipan Akta Kematian Nomor 1471-KM-14122023-0031 tanggal {tgl:2023-12-15};',
'Bahwa sejak ayahnya meninggal dunia, anak tersebut tinggal dan diasuh oleh penghadap;',
'Bahwa anak yang masih di bawah umur (belum mencapai umur 18 tahun dan belum pernah kawin) dan berada di bawah perwalian penghadap adalah **HAFIZ RABBANI MULIA**, lahir tanggal {tgl:2011-09-07} ({usia:2011-09-07}), yang belum cakap melakukan perbuatan hukum;',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah untuk mengambil Sertifikat Hak Milik Nomor 09514 yang terletak di Kota Pekanbaru, Kecamatan Marpoyan Damai, yang menjadi agunan pada Bank Mandiri atas nama almarhum **IRMAN** dengan nomor rekening 108-00-2050732-4, serta untuk keperluan administrasi lainnya;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **REPIT BIN DAHLAN**, adik kandung penghadap, menerangkan bahwa suami penghadap telah meninggal dunia pada tanggal {tgl:2023-11-26} karena sakit, anak diasuh oleh penghadap dengan baik, dan permohonan diajukan untuk mengambil sertifikat tanah yang diagunkan di Bank Mandiri;',
'- Saksi **ERNAWAN SUKANTO BIN SUPARDI** memberikan keterangan yang bersesuaian dengan saksi pertama;',
'Bahwa berdasarkan Penetapan Pengadilan Agama Pekanbaru Nomor 111/Pdt.P/2026/PA.Pbr tanggal {tgl:2026-06-11}, penghadap telah ditetapkan sebagai **Wali** dari anak kandungnya **HAFIZ RABBANI MULIA**;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'101/Pdt.P/2026/PA.Pbr': [
'Bahwa penghadap bernama **YOSI YULASRI BINTI ZULKIFLI**, NIK 1371076909800001, perempuan, lahir di Surian pada tanggal {tgl:1980-09-29} ({usia:1980-09-29}), agama Islam, pendidikan SLTA, bertempat tinggal di Jl. Suka Karya Perum Biru Asri No. B.7, RT 007 RW 004, Kelurahan Tuah Karya, Kota Pekanbaru, adalah ibu kandung dari anak yang dimohonkan perwalian;',
'Bahwa penghadap telah melangsungkan perkawinan dengan **ROBBY BIN NELFENDIUS** pada tanggal {tgl:2007-03-29} sebagaimana Kutipan Akta Nikah Nomor 060/02/IV/2007 yang dikeluarkan oleh Kantor Urusan Agama Kecamatan Pantai Cermin, Kabupaten Solok, Provinsi Sumatera Barat;',
'Bahwa dari perkawinan tersebut penghadap dikaruniai 2 (dua) orang anak, yaitu:',
'- **NATASYA BINTI ROBBY**, perempuan, lahir di Padang pada tanggal {tgl:2008-07-08} ({usia:2008-07-08}), sebagaimana Akta Kelahiran Nomor 145/09/T tanggal {tgl:2009-01-06};',
'- **FARID ATALLAH BIN ROBBY**, laki-laki, lahir di Pekanbaru pada tanggal {tgl:2015-12-18} ({usia:2015-12-18}), sebagaimana Akta Kelahiran Nomor 1471-LU-29122015-0072 tanggal {tgl:2015-12-30};',
'Bahwa suami penghadap, **ROBBY BIN NELFENDIUS**, telah meninggal dunia di Bukittinggi pada tanggal {tgl:2025-04-04} karena sakit, sebagaimana Kutipan Akta Kematian Nomor 1471-KM-07012026-0028 tanggal {tgl:2026-01-08};',
'Bahwa sejak ayahnya meninggal dunia, anak-anak tinggal bersama dan diasuh oleh penghadap dengan baik dan penuh kasih sayang, serta kebutuhan anak-anak tercukupi;',
'Bahwa selama perkawinan, penghadap dan almarhum suaminya memperoleh harta bersama berupa sebidang tanah dan bangunan dengan Sertifikat Hak Milik Nomor 5847, Surat Ukur tanggal {tgl:2009-11-16} Nomor 08052/Tuah Karya/2009, NIB 05.01.08.03.07975, terdaftar atas nama penghadap;',
'Bahwa anak yang masih di bawah umur dan berdasarkan penetapan berada di bawah perwalian penghadap adalah **FARID ATALLAH BIN ROBBY**, lahir tanggal {tgl:2015-12-18} ({usia:2015-12-18}), yang belum cakap melakukan perbuatan hukum;',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah untuk menandatangani akta peralihan hak atas tanah dan bangunan SHM Nomor 5847 tersebut serta untuk memenuhi syarat pinjaman Kredit Usaha Rakyat (KUR) pada Bank BNI KCP Tangkerang, guna memenuhi kebutuhan hidup dan biaya pendidikan anak-anak;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **IRSA AKSELLINI BINTI ABDUL HALIM** menerangkan bahwa suami penghadap meninggal dunia pada tanggal {tgl:2025-04-04} karena sakit, saksi melihat jenazah dan ikut mengantar ke pemakaman, anak-anak diasuh dengan baik oleh penghadap, penghadap tidak boros, baik dalam mengelola keuangan, serta tidak pernah mengonsumsi minuman keras maupun narkoba;',
'- Saksi **NOVA SRIMAIZA BINTI ZAFRI AMIR** memberikan keterangan yang bersesuaian dengan saksi pertama, dan menerangkan bahwa permohonan diajukan untuk permohonan kredit dan peralihan hak atas tanah harta peninggalan almarhum;',
'Bahwa berdasarkan Penetapan Pengadilan Agama Pekanbaru Nomor 101/Pdt.P/2026/PA.Pbr tanggal {tgl:2026-06-19}, anak bernama **FARID ATALLAH BIN ROBBY** ditetapkan berada di bawah perwalian penghadap untuk melakukan perbuatan hukum tertentu di dalam atau di luar pengadilan;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'3/Pdt.P/2026/PN Bkn': [
'Bahwa penghadap bernama **SARMIDA**, perempuan, lahir di Pulau Pandak pada tanggal {tgl:1985-06-13} ({usia:1985-06-13}), agama Islam, pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Petapahan, RT 048 RW 015, Desa Petapahan, Kecamatan Tapung, Kabupaten Kampar, Provinsi Riau, adalah ibu kandung dari anak-anak yang dimohonkan perwalian;',
'Bahwa penghadap telah melangsungkan perkawinan dengan **SYAFRI YULIS** pada tanggal {tgl:2007-03-29} sebagaimana Kutipan Akta Nikah Nomor 189/29/III/2007 yang dikeluarkan oleh Kantor Urusan Agama Kecamatan Kampar;',
'Bahwa dari perkawinan tersebut penghadap dikaruniai 3 (tiga) orang anak, yaitu:',
'- **DESWIKA PERTIWI**, lahir di Kabun pada tanggal {tgl:2007-12-25} ({usia:2007-12-25}), telah dewasa;',
'- anak kedua, lahir di Bangkinang pada tanggal {tgl:2009-07-31} ({usia:2009-07-31}), sebagaimana Kutipan Akta Kelahiran Nomor 1401-LU-16082012-0001 tanggal {tgl:2012-08-16};',
'- anak ketiga, lahir di Bangkinang pada tanggal {tgl:2011-09-14} ({usia:2011-09-14}), sebagaimana Kutipan Akta Kelahiran Nomor 1401-LU-28062012-0002 tanggal {tgl:2012-06-28};',
'Bahwa suami penghadap, **SYAFRI YULIS**, telah meninggal dunia di Kampar pada tanggal {tgl:2021-04-03} karena sakit, sebagaimana Kutipan Akta Kematian yang dikeluarkan oleh Dinas Kependudukan dan Pencatatan Sipil Kabupaten Kampar tanggal {tgl:2021-06-03};',
'Bahwa almarhum meninggalkan harta berupa sebidang tanah kosong dengan Sertipikat Hak Milik Nomor 2766 yang terletak di Desa Petapahan, Kecamatan Tapung, Kabupaten Kampar, Surat Ukur Nomor 00338/Petapahan/2010 tanggal {tgl:2010-01-19}, terdaftar atas nama **SYAFRI YULIS**;',
'Bahwa anak-anak yang masih di bawah umur dan berada di bawah kekuasaan penghadap adalah anak kedua (lahir {tgl:2009-07-31}) dan anak ketiga (lahir {tgl:2011-09-14}), yang merupakan ahli waris almarhum dan belum cakap melakukan perbuatan hukum;',
'Bahwa maksud penghadap mengajukan permohonan adalah untuk menjual tanah tersebut guna modal usaha serta biaya pemeliharaan dan pendidikan anak-anak, dengan harga yang wajar sesuai harga pasaran, dan tanah tersebut bukan rumah kediaman penghadap dan anak-anaknya;',
'Bahwa para ahli waris lainnya telah menyetujui dan memberikan kuasa kepada penghadap sebagaimana Surat Keterangan Ahli Waris Nomor 472.12/KET/Pth-Tp/2025/274, Surat Pernyataan Ahli Waris, dan Surat Kuasa Ahli Waris tanggal {tgl:2025-10-02};',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **TUKIMAN**, saudara jauh penghadap, menerangkan bahwa suami penghadap meninggal dunia pada tanggal {tgl:2021-04-03} karena sakit, dua anak penghadap masih di bawah umur, penghadap ibu yang baik dan bertanggung jawab, memiliki penghasilan sendiri dari usaha bengkel dan laundry, anak-anak dalam keadaan sejahtera, serta tidak ada pihak yang keberatan atas rencana penjualan tanah;',
'- Saksi **JESAYA BARUS**, tetangga penghadap, memberikan keterangan yang bersesuaian dengan saksi pertama;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Bangkinang Nomor 3/Pdt.P/2026/PN Bkn tanggal {tgl:2026-01-28}, penghadap diberi izin menjalankan kekuasaan sebagai orang tua untuk mewakili anak-anaknya melakukan perbuatan hukum menjual, mengurus administrasi, serta menandatangani surat-surat pada PPAT maupun Badan Pertanahan Nasional Kabupaten Kampar yang berhubungan dengan jual beli dan balik nama tanah SHM Nomor 2766 atas nama **SYAFRI YULIS**;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak-anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'13/Pdt.P/2026/PN Bkn': [
'Bahwa penghadap bernama **JAYA SAPUTRA**, laki-laki, lahir di Siak pada tanggal {tgl:1993-03-15} ({usia:1993-03-15}), agama Islam, pekerjaan wiraswasta (usaha kuliner nasi uduk), bertempat tinggal di Desa Bukit Payung, Kecamatan Bangkinang, Kabupaten Kampar, Provinsi Riau, adalah ayah kandung dari anak-anak yang dimohonkan perwalian;',
'Bahwa penghadap telah melangsungkan perkawinan secara agama Islam dengan **ETI NUR KHASANAH** pada tanggal {tgl:2012-06-30} sebagaimana Kutipan Akta Nikah Nomor 159/06/VII/2012 yang dikeluarkan oleh Kantor Urusan Agama Kecamatan Bangkinang Seberang;',
'Bahwa dari perkawinan tersebut penghadap dikaruniai 2 (dua) orang anak laki-laki yang keduanya masih di bawah umur, yaitu:',
'- anak pertama, laki-laki, lahir di Bangkinang pada tahun 2012;',
'- anak kedua, laki-laki, lahir pada tahun 2019;',
'Bahwa istri penghadap, **ETI NUR KHASANAH**, telah meninggal dunia pada tanggal {tgl:2026-02-09} karena sakit gagal ginjal di Rumah Sakit Madani, sebagaimana Kutipan Akta Kematian Nomor 1401-KM-09032026-0003 tanggal {tgl:2026-03-09} dan Surat Keterangan Kematian Nomor 474.3/PEM-BKP/055 dari Pemerintah Desa Bukit Payung;',
'Bahwa ahli waris almarhumah adalah penghadap dan kedua anaknya, sebagaimana Surat Keterangan Susunan Ahli Waris Nomor 474.3/Pem-BKP/063 tanggal {tgl:2026-02-13};',
'Bahwa almarhumah meninggalkan harta bersama berupa sebidang tanah dan bangunan dengan Sertifikat Hak Milik Nomor 01911 yang terletak di Desa Bukit Payung, Kecamatan Bangkinang, Kabupaten Kampar, Surat Ukur Nomor 00828/2020 tanggal {tgl:2020-07-06}, luas ±550 m², tercatat atas nama **JAYA SAPUTRA**;',
'Bahwa sejak ibunya meninggal dunia, anak-anak dirawat oleh penghadap sendiri dengan dibantu oleh orang tua penghadap;',
'Bahwa maksud penghadap mengajukan permohonan adalah untuk menjaminkan tanah dan bangunan tersebut ke bank guna memperluas usaha agar dapat mencukupi kebutuhan keluarga dan anak-anak; sertifikat tersebut saat ini masih digadaikan kepada orang pribadi untuk keperluan biaya berobat dan pemakaman almarhumah;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **TUTI FITRIAH**, adik ipar penghadap, menerangkan bahwa istri penghadap meninggal dunia pada tanggal {tgl:2026-02-09} karena sakit gagal ginjal, rumah bersertifikat Nomor 01911 diperoleh setelah menikah, anak-anak dirawat penghadap dibantu orang tuanya, dan penjaminan bertujuan memperluas usaha untuk mencukupi kebutuhan keluarga;',
'- Saksi **MHD. INDRA AFANDI**, sepupu penghadap, memberikan keterangan yang bersesuaian dengan saksi pertama;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Bangkinang Nomor 13/Pdt.P/2026/PN Bkn tanggal {tgl:2026-04-02}, penghadap selaku ayah kandung diberi izin untuk menjaminkan, dengan cara yang sesuai hukum, harta peninggalan almarhumah **ETI NUR KHASANAH** berupa tanah dan bangunan SHM Nomor 01911 tersebut, termasuk bagian anak-anaknya yang masih di bawah umur;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak-anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'109/Pdt.P/2026/PA.Bkn': [
'Bahwa penghadap bernama **SITI JUMILAH BINTI I TUMIRIN**, NIK 1471095004850001, perempuan, lahir di Terantang pada tanggal {tgl:1985-08-10} ({usia:1985-08-10}), agama Islam, pendidikan SLTA, pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Dusun III Desa Hangtuah, RT 028 RW 006, Desa Hangtuah, Kecamatan Perhentian Raja, Kabupaten Kampar, Provinsi Riau, adalah ibu kandung dari anak-anak yang dimohonkan perwalian;',
'Bahwa penghadap telah melangsungkan perkawinan dengan **MASANDI BIN JABAR** pada tanggal {tgl:2005-09-16} sebagaimana Kutipan Akta Nikah Nomor 349/03/XI/2005 yang dikeluarkan oleh Kantor Urusan Agama Kecamatan Siak Hulu, Kabupaten Kampar;',
'Bahwa dari perkawinan tersebut penghadap dikaruniai 3 (tiga) orang anak, yaitu:',
'- **MUHAMMAD IRSYAD ALVARO BIN MASANDI**, laki-laki, lahir di Pekanbaru pada tanggal {tgl:2011-12-16} ({usia:2011-12-16}), sebagaimana Kutipan Akta Kelahiran Nomor 1471-LT-24102012-0033 tanggal {tgl:2012-10-25};',
'- **INTAN ZAKIYA BINTI MASANDI**, perempuan, lahir di Pekanbaru pada tanggal {tgl:2014-04-09} ({usia:2014-04-09}), sebagaimana Kutipan Akta Kelahiran Nomor 1471-LT-28042017-0009 tanggal {tgl:2017-05-04};',
'- **AQILA AZKADINA SHAZFA BINTI MASANDI**, perempuan, lahir di Kabupaten Kampar pada tanggal {tgl:2020-11-13} ({usia:2020-11-13}), sebagaimana Kutipan Akta Kelahiran Nomor 1401-LT-10092024-0030 tanggal {tgl:2024-09-11};',
'Bahwa suami penghadap, **MASANDI BIN JABAR**, telah meninggal dunia di Kabupaten Kampar pada tanggal {tgl:2024-11-04}, sebagaimana Kutipan Akta Kematian Nomor 1401-KM-22012025-0009 tanggal {tgl:2025-01-22} yang dikeluarkan oleh Dinas Kependudukan dan Pencatatan Sipil Kabupaten Kampar;',
'Bahwa sejak ayahnya meninggal dunia, ketiga anak tersebut tinggal bersama dan diasuh oleh penghadap dengan baik, tidak pernah ditelantarkan maupun mengalami kekerasan; penghadap dalam keadaan sehat berdasarkan surat keterangan dokter UPT Puskesmas Pantai Raja dan tidak memiliki catatan kriminal berdasarkan SKCK Polres Kampar tanggal {tgl:2026-08-12};',
'Bahwa anak-anak yang masih di bawah umur (belum mencapai umur 18 tahun dan belum pernah kawin) dan berada di bawah perwalian penghadap adalah 3 (tiga) orang, yaitu:',
'- **MUHAMMAD IRSYAD ALVARO BIN MASANDI**, lahir tanggal {tgl:2011-12-16} ({usia:2011-12-16});',
'- **INTAN ZAKIYA BINTI MASANDI**, lahir tanggal {tgl:2014-04-09} ({usia:2014-04-09});',
'- **AQILA AZKADINA SHAZFA BINTI MASANDI**, lahir tanggal {tgl:2020-11-13} ({usia:2020-11-13});',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah untuk pengurusan administrasi harta peninggalan almarhum di Badan Pertanahan Nasional (BPN), dan pihak keluarga telah sepakat menunjuk penghadap sebagai wali;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **MERIDA BR PURBA BINTI PURBA**, tetangga penghadap, menerangkan bahwa suami penghadap telah meninggal dunia, ketiga anak diasuh penghadap dengan baik tanpa kekerasan maupun penelantaran, penghadap tidak memiliki sifat tercela, dan permohonan diajukan untuk pengurusan administrasi di BPN;',
'- Saksi **NURCAHAYA SIMAMORA BINTI SIMAMORA**, tetangga penghadap, memberikan keterangan yang bersesuaian dengan saksi pertama;',
'Bahwa berdasarkan Penetapan Pengadilan Agama Bangkinang Nomor 109/Pdt.P/2026/PA.Bkn tanggal {tgl:2026-09-08}, penghadap telah ditetapkan sebagai Pemegang Kuasa atau **Wali** dari ketiga anaknya yang masih di bawah umur tersebut, untuk mewakili segala kepentingan hukum ketiga anak baik di dalam maupun di luar pengadilan;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak-anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'95/Pdt.P/2026/PA.Bkn': [
'Bahwa penghadap bernama **NURHASNAH BINTI BASRI**, NIK 1401025212840006, perempuan, lahir di Pulau Jambu pada tanggal {tgl:1984-12-12} ({usia:1984-12-12}), agama Islam, pendidikan D3, pekerjaan Wiraswasta, bertempat tinggal di Jalan Cikditiro Perumahan Gria Puri Husada Blok J-22, Dusun Mahmud Marzuki, RT 004 RW 003, Desa Kumantan, Kecamatan Bangkinang Kota, Kabupaten Kampar, adalah ibu kandung dari anak-anak yang dimohonkan perwalian;',
'Bahwa penghadap telah melangsungkan perkawinan dengan **HAFIZ AL FAJRI BIN H. BASRI GARIB** pada tanggal {tgl:2007-08-02} sebagaimana Kutipan Akta Nikah Nomor 365/19/VIII/2007 yang dikeluarkan oleh Kantor Urusan Agama Kecamatan Kampar, Kabupaten Kampar, dan perkawinan tersebut telah putus karena perceraian sebagaimana Akta Cerai Nomor 0884/AC/2020/PA.Bkn tanggal {tgl:2020-11-25} yang dikeluarkan oleh Pengadilan Agama Bangkinang;',
'Bahwa dari perkawinan tersebut penghadap dikaruniai 3 (tiga) orang anak, yaitu:',
'- **MUHAMMAD DAFFA ADITYA BIN HAFIZ AL FAJRI**, laki-laki, lahir di Pekanbaru pada tanggal {tgl:2008-08-22} ({usia:2008-08-22}), sebagaimana Akta Kelahiran Nomor 1401022208080001 tanggal {tgl:2012-12-28};',
'- **AISYAH KHUMAIRAH BINTI HAFIZ AL FAJRI**, perempuan, lahir di Pekanbaru pada tanggal {tgl:2010-11-02} ({usia:2010-11-02}), sebagaimana Akta Kelahiran Nomor 1401024211100001 tanggal {tgl:2011-06-10};',
'- **ANISA NAJLA SHAFIRA BINTI HAFIZ AL FAJRI**, perempuan, lahir di Pekanbaru pada tanggal {tgl:2012-12-10} ({usia:2012-12-10}), sebagaimana Akta Kelahiran Nomor 1401025012120001 tanggal {tgl:2013-01-11};',
'Bahwa mantan suami penghadap sekaligus ayah kandung anak-anak, **HAFIZ AL FAJRI BIN H. BASRI GARIB**, telah meninggal dunia di Rumah Sakit Umum Bangkinang pada tanggal {tgl:2026-07-19}, sebagaimana Kutipan Akta Kematian Nomor 1401-KM-22072026-0031 tanggal {tgl:2026-07-22} yang dikeluarkan oleh Dinas Kependudukan dan Pencatatan Sipil Kabupaten Kampar;',
'Bahwa ketiga anak tersebut dirawat dan diasuh oleh penghadap dengan baik, tanpa kekerasan maupun penelantaran; penghadap dalam keadaan sehat berdasarkan Surat Keterangan Sehat UPTD Puskesmas Bangkinang dan tidak memiliki catatan kriminal berdasarkan SKCK Polres Kampar Nomor SKCK/3944/VII/YAN.2.3/2026;',
'Bahwa anak-anak yang pada saat penetapan masih di bawah umur dan ditetapkan berada di bawah perwalian penghadap adalah 3 (tiga) orang, yaitu:',
'- **MUHAMMAD DAFFA ADITYA**, lahir tanggal {tgl:2008-08-22} ({usia:2008-08-22});',
'- **AISYAH KHUMAIRAH**, lahir tanggal {tgl:2010-11-02} ({usia:2010-11-02});',
'- **ANISA NAJLA SHAFIRA**, lahir tanggal {tgl:2012-12-10} ({usia:2012-12-10});',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah untuk mengurus administrasi Taspen atas nama almarhum **HAFIZ AL FAJRI**, dan pihak keluarga telah sepakat menunjuk penghadap sebagai wali;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **NURBASRAINI BINTI BASRI**, kakak kandung penghadap, menerangkan bahwa penghadap dan almarhum telah bercerai pada tahun 2020, almarhum meninggal dunia pada bulan Juli 2026, ketiga anak dirawat dan diasuh penghadap dengan baik, penghadap tidak memiliki sifat tercela, dan permohonan diajukan untuk mengurus administrasi Taspen;',
'- Saksi **NURFITRINELI BINTI ALI ANWAR**, tetangga penghadap, memberikan keterangan yang bersesuaian dengan saksi pertama;',
'Bahwa berdasarkan Penetapan Pengadilan Agama Bangkinang Nomor 95/Pdt.P/2026/PA.Bkn tanggal {tgl:2026-08-20}, penghadap telah ditetapkan sebagai Pemegang Kuasa atau **Wali** dari ketiga anaknya tersebut, untuk mewakili segala kepentingan hukum ketiga anak baik di dalam maupun di luar pengadilan;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak-anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'45/Pdt.P/2026/PN Dum': [
'Bahwa penghadap bernama **DESMAULITA BR. SITUMORANG**, perempuan, lahir di Sibolga pada tanggal {tgl:1966-12-08} ({usia:1966-12-08}), pekerjaan Mengurus Rumah Tangga, bertempat tinggal di Jalan Jenderal Sudirman Gang Karya I, RT 001, Kelurahan Buluh Kasap, Kecamatan Dumai Timur, Kota Dumai, Provinsi Riau, adalah nenek kandung (ibu kandung dari almarhum ayah) anak yang dimohonkan perwalian;',
'Bahwa anak penghadap, **EDWARD RICHARDO SIMANJUNTAK**, telah melangsungkan perkawinan dengan **KRISTINA WATI SIMAMORA** pada tanggal {tgl:2016-11-17} sebagaimana Kutipan Akta Perkawinan Nomor 1472-KW-11102018-0004 yang dikeluarkan oleh Dinas Kependudukan dan Pencatatan Sipil Kota Dumai;',
'Bahwa dari perkawinan tersebut lahir 1 (satu) orang anak perempuan, yaitu **AMORA PATRICIA SIMANJUNTAK**, lahir di Dumai pada tanggal {tgl:2017-08-12} ({usia:2017-08-12}), sebagaimana Kutipan Akta Kelahiran Nomor 1472-LT-23112018-0033 tanggal {tgl:2026-05-04}, yang saat ini bersekolah di kelas 2 SD Swasta Estomihi Dumai;',
'Bahwa kedua orang tua anak tersebut telah meninggal dunia karena sakit, yaitu:',
'- ibu kandung, **KRISTINA WATI SIMAMORA**, meninggal dunia pada tanggal {tgl:2025-11-07}, sebagaimana Kutipan Akta Kematian Nomor 1472-KM-02042026-0001;',
'- ayah kandung, **EDWARD RICHARDO SIMANJUNTAK**, meninggal dunia di Dumai pada tanggal {tgl:2026-03-12}, sebagaimana Kutipan Akta Kematian Nomor 1472-KM-02042026-0002;',
'Bahwa sejak kedua orang tuanya meninggal dunia, anak tersebut tinggal bersama, diasuh, dan dibiayai sekolahnya oleh penghadap sebagaimana Kartu Keluarga, dan penghadap telah membuat Surat Pernyataan Tidak Akan Menelantarkan Anak serta Surat Pernyataan Bersedia Menjadi Wali tanggal {tgl:2026-06-09};',
'Bahwa anak yang masih di bawah umur dan berada di bawah perwalian penghadap adalah **AMORA PATRICIA SIMANJUNTAK**, lahir tanggal {tgl:2017-08-12} ({usia:2017-08-12});',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah untuk mengurus diri dan hak-hak anak atas bagian peninggalan kedua orang tuanya, termasuk pencairan Jaminan Hari Tua/Tunjangan Kematian BPJS Ketenagakerjaan almarhum **EDWARD RICHARDO SIMANJUNTAK** Nomor 1472 0212 0689 0001, serta keperluan administrasi pendidikan dan kependudukan anak;',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **YUSNANI**, tetangga penghadap, menerangkan bahwa kedua orang tua anak telah meninggal dunia karena sakit asam lambung, anak diasuh dan dirawat dengan baik oleh penghadap tanpa kekerasan, dan tidak ada keberatan dari pihak lain atas permohonan tersebut;',
'- Saksi **NELVIDA M. SIREGAR** memberikan keterangan yang bersesuaian, serta menerangkan bahwa keluarga dari pihak ibu anak telah mengetahui permohonan ini dan biaya sekolah anak ditanggung oleh penghadap;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Dumai Nomor 45/Pdt.P/2026/PN Dum tanggal {tgl:2026-06-18}, penghadap telah ditetapkan sebagai **Wali** berdasarkan undang-undang dari anak **AMORA PATRICIA SIMANJUNTAK**, dan Panitera diperintahkan mengirimkan salinan penetapan kepada Balai Harta Peninggalan Medan untuk dicatat;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
'55/Pdt.P/2026/PN Dum': [
'Bahwa penghadap bernama **ABDUL GANI**, NIK 1472051312600001, laki-laki, lahir pada tanggal {tgl:1960-12-13} ({usia:1960-12-13}), pekerjaan buruh harian lepas, bertempat tinggal di Jalan Cek Porek (Parit Masjid), RT 004, Kelurahan Teluk Makmur, Kecamatan Medang Kampai, Kota Dumai, Provinsi Riau, adalah kakek kandung (ayah kandung dari almarhum ayah) anak-anak yang dimohonkan perwalian;',
'Bahwa anak penghadap, **JON HAMRI**, telah melangsungkan perkawinan dengan **NUR HAINI** pada tanggal {tgl:2010-01-24} sebagaimana Kutipan Akta Nikah Nomor 016/16/I/2010;',
'Bahwa dari perkawinan tersebut lahir 2 (dua) orang anak, yaitu:',
'- **NUR RIZKI MAULANA**, laki-laki, lahir di Dumai pada tanggal {tgl:2010-10-27} ({usia:2010-10-27}), sebagaimana Kutipan Akta Kelahiran Nomor 1472CLU2611201003813 tanggal {tgl:2010-11-26}, saat ini bersekolah di kelas 1 SMA;',
'- **SYAHIRAH NUR IZATI**, perempuan, lahir di Dumai pada tanggal {tgl:2015-01-18} ({usia:2015-01-18}), sebagaimana Kutipan Akta Kelahiran Nomor 1472-LU-05022015-0022 tanggal {tgl:2015-02-05}, saat ini bersekolah di SD;',
'Bahwa kedua orang tua anak-anak tersebut telah meninggal dunia, yaitu:',
'- ibu kandung, **NUR HAINI**, meninggal dunia pada tanggal {tgl:2024-08-02} karena sakit, sebagaimana Kutipan Akta Kematian Nomor 1472-KM-25022025-0003 tanggal {tgl:2025-02-25};',
'- ayah kandung, **JON HAMRI**, meninggal dunia pada tanggal {tgl:2026-03-09}, sebagaimana Kutipan Akta Kematian tanggal {tgl:2026-03-12} yang dikeluarkan oleh Pejabat Pencatatan Sipil Kota Dumai;',
'Bahwa sejak kedua orang tuanya meninggal dunia, anak-anak tersebut tinggal bersama penghadap sebagaimana Kartu Keluarga Nomor 1472051601070035, dan seluruh biaya pendidikan serta kebutuhan sehari-hari ditanggung oleh penghadap; penghadap telah membuat Surat Pernyataan Bersedia Menjadi Wali dan Surat Pernyataan Tidak Akan Menelantarkan Anak tanggal {tgl:2026-06-22};',
'Bahwa anak-anak yang masih di bawah umur dan berada di bawah perwalian penghadap adalah 2 (dua) orang, yaitu:',
'- **NUR RIZKI MAULANA**, lahir tanggal {tgl:2010-10-27} ({usia:2010-10-27});',
'- **SYAHIRAH NUR IZATI**, lahir tanggal {tgl:2015-01-18} ({usia:2015-01-18});',
'Bahwa maksud penghadap mengajukan permohonan perwalian adalah untuk mengurus diri dan hak-hak anak atas bagian peninggalan kedua orang tuanya, termasuk pencairan tabungan/tunjangan kematian BPJS Ketenagakerjaan almarhum **JON HAMRI** Nomor 1472 0502 0285 0001, serta keperluan pendidikan dan administrasi kependudukan anak-anak; para ahli waris telah memberikan kuasa sebagaimana Surat Kuasa Ahli Waris dan Surat Keterangan Ahli Waris tanggal {tgl:2026-03-10};',
'Bahwa keterangan saksi-saksi di persidangan pada pokoknya sebagai berikut:',
'- Saksi **AZWAR ANAS**, yang mengenal penghadap lebih dari 30 tahun, menerangkan bahwa kedua orang tua anak-anak telah meninggal dunia, anak-anak tinggal bersama dan dibiayai oleh penghadap, penghadap menyayangi cucu-cucunya, serta hubungan penghadap dengan orang tua almarhumah **NUR HAINI** yang tinggal di Selat Panjang baik-baik saja;',
'- Saksi **RAHMAD HIDAYAT** memberikan keterangan yang bersesuaian dengan saksi pertama;',
'Bahwa berdasarkan Penetapan Pengadilan Negeri Dumai Nomor 55/Pdt.P/2026/PN Dum tanggal {tgl:2026-08-13}, penghadap telah ditetapkan sebagai **Wali** berdasarkan undang-undang dari anak-anak **NUR RIZKI MAULANA** dan **SYAHIRAH NUR IZATI**, dan Panitera diperintahkan mengirimkan salinan penetapan kepada Balai Harta Peninggalan Medan untuk dicatat;',
'Bahwa penghadap bersedia menjalankan tugas sebagai Wali dengan sebaik-baiknya, mengurus kepentingan dan harta kekayaan anak-anak di bawah umur tersebut dengan penuh tanggung jawab, serta bersedia diawasi oleh Balai Harta Peninggalan Medan selaku Wali Pengawas.'
],
};
